// Tailwind utilities grouped by component. Keep the marker class for descendant variants.
export const accountStyles = {
  accountShell: [
    "account-shell mt-0 mr-auto mb-0 ml-auto grid text-[#1e1e1e] [@media(max-width:767px)]:block",
    "max-w-320 gap-6 pt-8 pr-8 pb-20 pl-8 grid-cols-[250px_minmax(0,1fr)]",
    "[@media(max-width:1023px)]:pt-6 [@media(max-width:1023px)]:pr-6",
    "[@media(max-width:1023px)]:pb-16 [@media(max-width:1023px)]:pl-6",
    "[@media(max-width:1023px)]:grid-cols-[210px_minmax(0,1fr)] [@media(max-width:1023px)]:gap-5",
    "[@media(max-width:767px)]:pt-5 [@media(max-width:767px)]:pr-4",
    "[@media(max-width:767px)]:pb-12 [@media(max-width:767px)]:pl-4",
  ].join(" "),
  accountSidebar: [
    "account-sidebar self-start sticky [&_nav]:[border-top:1px_solid_#ddd] [&_nav_a]:flex",
    "[&_nav_a]:justify-between [&_nav_a]:[border-bottom:1px_solid_#ddd]",
    "[&_nav_a]:[transition:background_.2s] [&_nav_a:hover]:bg-[#f3f3f1]",
    "[@media(max-width:767px)]:static [@media(max-width:767px)]:mb-5",
    "[@media(max-width:767px)]:[&>.account-eyebrow]:hidden",
    "[@media(max-width:767px)]:[&_nav]:flex [@media(max-width:767px)]:[&_nav]:gap-[6px]",
    "[@media(max-width:767px)]:[&_nav]:[border-top:0] [@media(max-width:767px)]:[&_nav]:pb-2",
    "[@media(max-width:767px)]:[&_nav_a]:shrink-0",
    "[@media(max-width:767px)]:[&_nav_a]:whitespace-nowrap",
    "[@media(max-width:767px)]:[&_nav_a]:[border:0]",
    "[@media(max-width:767px)]:[&_nav_a_span]:hidden pt-6 pr-4 pb-6 pl-4 bg-[#e7e7e7]",
    "rounded-[26px] top-30 [&>.account-eyebrow]:pt-0 [&>.account-eyebrow]:pr-3",
    "[&>.account-eyebrow]:pb-0 [&>.account-eyebrow]:pl-3 [&>.account-eyebrow]:tracking-[.22em]",
    "[&_nav]:[border:0] [&_nav]:bg-white [&_nav]:rounded-[20px] [&_nav]:overflow-hidden",
    "[&_nav]:mt-4 [&_nav]:mr-0 [&_nav]:mb-4 [&_nav]:ml-0 [&_nav_a]:pt-[18px] [&_nav_a]:pr-[14px]",
    "[&_nav_a]:pb-[18px] [&_nav_a]:pl-[14px] [&_nav_a]:items-center [&_nav_a]:gap-3",
    "[&_nav_a]:border-[#f0f0f0] [&_nav_a]:text-[13px] [&_nav_a>svg]:text-[var(--beecah-blue)]",
    "[&_nav_a>svg]:shrink-0 [&_nav_a.is-active]:[background:var(--beecah-black)]",
    "[&_nav_a.is-active]:text-white [&_nav_a.is-active]:border-[var(--beecah-black)]",
    "[&_nav_a.is-active>svg]:text-white [&_nav_a:hover:not(.is-active)]:bg-[#f5f5f5]",
    "[@media(max-width:1023px)]:pt-5 [@media(max-width:1023px)]:pr-3",
    "[@media(max-width:1023px)]:pb-5 [@media(max-width:1023px)]:pl-3",
    "[@media(max-width:767px)]:bg-transparent [@media(max-width:767px)]:pt-0",
    "[@media(max-width:767px)]:pr-0 [@media(max-width:767px)]:pb-0",
    "[@media(max-width:767px)]:pl-0 [@media(max-width:767px)]:flex",
    "[@media(max-width:767px)]:flex-wrap [@media(max-width:767px)]:justify-between",
    "[@media(max-width:767px)]:items-center [@media(max-width:767px)]:gap-3",
    "[@media(max-width:767px)]:[&_nav]:[order:3] [@media(max-width:767px)]:[&_nav]:w-full",
    "[@media(max-width:767px)]:[&_nav]:mt-0 [@media(max-width:767px)]:[&_nav]:mr-0",
    "[@media(max-width:767px)]:[&_nav]:mb-0 [@media(max-width:767px)]:[&_nav]:ml-0",
    "[@media(max-width:767px)]:[&_nav]:rounded-none",
    "[@media(max-width:767px)]:[&_nav]:bg-transparent",
    "[@media(max-width:767px)]:[&_nav]:overflow-x-auto",
    "[@media(max-width:767px)]:[&_nav]:pt-[2px] [@media(max-width:767px)]:[&_nav]:pr-[2px]",
    "[@media(max-width:767px)]:[&_nav]:pl-[2px] [@media(max-width:767px)]:[&_nav_a]:pt-3",
    "[@media(max-width:767px)]:[&_nav_a]:pr-[14px] [@media(max-width:767px)]:[&_nav_a]:pb-3",
    "[@media(max-width:767px)]:[&_nav_a]:pl-[14px]",
    "[@media(max-width:767px)]:[&_nav_a]:rounded-[12px]",
    "[@media(max-width:767px)]:[&_nav_a]:bg-[#f1f1ef]",
    "[@media(max-width:767px)]:[&_nav_a]:min-h-12 [@media(max-width:767px)]:[&_nav_a]:gap-2",
    "[@media(max-width:767px)]:[&_nav_a_.account-nav-label]:[display:inline]",
    "[@media(max-width:767px)]:[&_nav_a>svg]:w-4",
  ].join(" "),
  accountStoreLink: [
    "account-store-link flex items-center justify-between text-[#606060]",
    "[@media(max-width:767px)]:max-w-none pt-0 pr-[10px] pb-[26px] pl-[10px] text-[12px]",
    "[@media(max-width:767px)]:pt-0 [@media(max-width:767px)]:pr-0",
    "[@media(max-width:767px)]:pb-0 [@media(max-width:767px)]:pl-0",
    "[@media(max-width:767px)]:min-h-11 [@media(max-width:767px)]:gap-3",
  ].join(" "),
  accountEyebrow: [
    "account-eyebrow text-[10px] font-semibold tracking-[.16em] uppercase text-[#686868]",
  ].join(" "),
  accountLogout: [
    "account-logout flex items-center gap-[10px] text-[12px] [&:disabled]:opacity-[.5]",
    "[@media(max-width:767px)]:ml-0 bg-white w-full justify-center rounded-[14px] text-[#1e1e1e]",
    "min-h-12 [&:hover]:bg-[#f5f5f5] [@media(max-width:767px)]:w-auto",
    "[@media(max-width:767px)]:pt-0 [@media(max-width:767px)]:pr-3",
    "[@media(max-width:767px)]:pb-0 [@media(max-width:767px)]:pl-3",
    "[@media(max-width:767px)]:mt-0 [@media(max-width:767px)]:mr-0",
    "[@media(max-width:767px)]:mb-0 [@media(max-width:767px)]:bg-[#f1f1ef]",
    "[@media(max-width:767px)]:text-[12px] [@media(max-width:767px)]:min-h-11",
  ].join(" "),
  accountContent: ["account-content min-w-0"].join(" "),
  accountIntro: [
    "account-intro [&_h1]:leading-[1.1] [&>p:last-child]:text-[14px]",
    "[&>p:last-child]:text-[#686868] [&>p:last-child]:leading-[1.7] relative isolate",
    "overflow-hidden min-h-65 rounded-[26px] pt-9 pr-9 pb-9 pl-9 flex items-end text-white",
    '[&:after]:content-[""] [&:after]:absolute [&:after]:inset-0 [&:after]:z-[-1]',
    "[&:after]:bg-[linear-gradient(90deg,rgba(0,0,0,.65),rgba(0,0,0,.12))]",
    '[&_.account-eyebrow]:text-[#ffffffbf] [&_h1]:[font-family:"Haerins",serif]',
    "[&_h1]:font-normal [&_h1]:text-[clamp(32px,3.5vw,48px)] [&_h1]:tracking-[0]",
    "[&_h1]:wrap-anywhere [&_h1]:mt-[18px] [&_h1]:mr-0 [&_h1]:mb-3 [&_h1]:ml-0",
    "[@media(max-width:767px)]:min-h-55 [@media(max-width:767px)]:pt-[26px]",
    "[@media(max-width:767px)]:pr-[26px] [@media(max-width:767px)]:pb-[26px]",
    "[@media(max-width:767px)]:pl-[26px] [@media(max-width:767px)]:rounded-[22px]",
    "[@media(max-width:767px)]:[&_h1]:text-[32px]",
  ].join(" "),
  accountPanel: [
    "account-panel [border-top:1px_solid_#cfcfcd] [scroll-margin-top:120px] [border:0]",
    "rounded-[26px] bg-[#f5f5f3] pt-7 pr-7 pb-7 pl-7 [@media(max-width:1023px)]:pt-6",
    "[@media(max-width:1023px)]:pr-6 [@media(max-width:1023px)]:pb-6",
    "[@media(max-width:1023px)]:pl-6 [@media(max-width:767px)]:pt-5",
    "[@media(max-width:767px)]:pr-5 [@media(max-width:767px)]:pb-5",
    "[@media(max-width:767px)]:pl-5 [@media(max-width:767px)]:rounded-[22px]",
  ].join(" "),
  accountSectionTitle: [
    "account-section-title flex items-center justify-between gap-5 [&_h2]:font-medium",
    "[&_h2]:mt-[6px] [@media(max-width:767px)]:gap-3 mb-[22px] [&_h2]:text-[23px]",
    "[&_h2]:tracking-[-.025em] [@media(max-width:1023px)]:flex-wrap",
    "[@media(max-width:767px)]:[&_h2]:text-[21px]",
  ].join(" "),
  accountCount: [
    "account-count rounded-full grid place-items-center text-[12px] bg-white [border:0] w-10",
    "h-10",
  ].join(" "),
  accountEmpty: [
    "account-empty max-w-full [&_h3]:leading-[1.3] [&_h3]:max-w-100 [&_p]:text-[13px]",
    "[&_p]:leading-[1.8] [&_p]:text-[#666] [&_p]:mt-[14px] [&_p]:mr-0 [&_p]:mb-6 [&_p]:ml-0",
    "bg-white rounded-[20px] pt-[30px] pr-[30px] pb-[30px] pl-[30px] [&_h3]:text-[22px]",
    "[&_h3]:tracking-[-.025em] [&_p]:max-w-110 [@media(max-width:767px)]:pt-6",
    "[@media(max-width:767px)]:pr-5 [@media(max-width:767px)]:pb-6",
    "[@media(max-width:767px)]:pl-5 [@media(max-width:767px)]:[&_h3]:text-[21px]",
  ].join(" "),
  accountPrimary: [
    "account-primary text-white inline-flex items-center justify-between text-[12px] min-h-12",
    "[background:var(--beecah-black)] rounded-[12px] pt-[15px] pr-5 pb-[15px] pl-5 gap-6",
    "[&:hover]:[background:var(--beecah-blue)]",
  ].join(" "),
  accountTextLink: [
    "account-text-link font-medium [text-underline-offset:5px] min-h-11 [align-content:center]",
    "text-[13px] no-underline text-[var(--beecah-blue)] [&:hover]:underline",
  ].join(" "),
  accountDetails: [
    "account-details grid gap-6 [&_dt]:text-[#777] [&_dt]:mb-[10px] [&_dd]:text-[14px]",
    "[&_dd]:wrap-anywhere bg-white pt-6 pr-6 pb-6 pl-6 rounded-[20px] grid-cols-[1fr_1fr]",
    "[&>div:nth-child(2)]:[grid-column:1/-1] [&>div:nth-child(2)]:[grid-row:2]",
    "[&_dt]:text-[12px] [@media(max-width:1023px)]:grid-cols-[1fr]",
    "[@media(max-width:1023px)]:[&>div:nth-child(2)]:[grid-column:auto]",
    "[@media(max-width:1023px)]:[&>div:nth-child(2)]:[grid-row:auto]",
    "[@media(max-width:767px)]:pt-5 [@media(max-width:767px)]:pr-5",
    "[@media(max-width:767px)]:pb-5 [@media(max-width:767px)]:pl-5",
  ].join(" "),
  accountAddresses: [
    "account-addresses grid grid-cols-[1fr_1fr] gap-4 [@media(max-width:1023px)]:grid-cols-[1fr]",
  ].join(" "),
  accountAddress: [
    "account-address min-w-0 wrap-anywhere [&_h3]:font-medium [&_h3]:text-[17px]",
    "[&_p]:text-[13px] [&_p]:text-[#606060] [&_p]:leading-[1.8] [border:0] bg-white",
    "rounded-[20px] pt-6 pr-6 pb-6 pl-6",
  ].join(" "),
  accountStatus: [
    "account-status inline-block leading-[1.5] pt-[6px] pr-[10px] pb-[6px] pl-[10px]",
    "bg-[#f0f1f4] text-[#2d416f] rounded-[8px] text-[11px]",
  ].join(" "),
  statusApproved: ["status-approved bg-[#edf4ee] text-[#315d3c]"].join(" "),
  statusPending: ["status-pending bg-[#fcf4e5] text-[#795a21]"].join(" "),
  statusRejected: ["status-rejected bg-[#faefec] text-[#924333]"].join(" "),
  statusCancelled: ["status-cancelled bg-[#faefec] text-[#924333]"].join(" "),
  accountEmptySmall: [
    "account-empty-small pt-7 pr-7 pb-7 pl-7 [&_h3]:text-[21px] [&_p]:mb-2",
  ].join(" "),
  accountOrder: [
    "account-order grid grid-cols-[1.1fr_1fr_auto] items-center",
    "[border-bottom:1px_solid_#e2e2e0] [transition:background_.2s] [&:hover]:bg-[#f6f6f3]",
    "[&_strong]:text-[13px] [&_strong]:font-medium [&_p]:text-[11px] [&_p]:text-[#777]",
    "[&_p]:mt-[7px] [@media(max-width:1023px)]:grid-cols-[1fr_auto]",
    "[@media(max-width:1023px)]:[&_.account-status]:[grid-column:1]",
    "[@media(max-width:1023px)]:[&_.account-status]:[grid-row:2]",
    "[@media(max-width:1023px)]:[&>strong]:[grid-column:2]",
    "[@media(max-width:1023px)]:[&>strong]:[grid-row:1]",
    "[@media(max-width:767px)]:[&_.account-status]:max-w-none pt-[22px] pr-[22px] pb-[22px]",
    "pl-[22px] gap-[14px] [&:last-child]:[border-bottom:0] [@media(max-width:767px)]:pt-5",
    "[@media(max-width:767px)]:pr-4 [@media(max-width:767px)]:pb-5",
    "[@media(max-width:767px)]:pl-4 [@media(max-width:767px)]:gap-x-[10px]",
    "[@media(max-width:767px)]:[&_.account-status]:text-[10px]",
  ].join(" "),
  accountOrderAction: [
    "account-order-action [grid-column:1/-1] text-[#2d416f]",
    "[@media(max-width:1023px)]:[grid-column:2] [@media(max-width:1023px)]:[grid-row:2]",
    "text-[12px]",
  ].join(" "),
  accountHelp: [
    "account-help flex justify-between gap-3 items-center [border-top:1px_solid_#ddd]",
    "text-[#666] [@media(max-width:767px)]:items-start [@media(max-width:767px)]:flex-col",
    "[border:0] pt-2 pr-3 pb-2 pl-3 text-[13px] [@media(max-width:767px)]:gap-0",
    "[@media(max-width:767px)]:pt-2 [@media(max-width:767px)]:pr-2",
    "[@media(max-width:767px)]:pb-2 [@media(max-width:767px)]:pl-2",
  ].join(" "),
  accountFormPage: [
    "account-form-page [&_h1]:tracking-[-.04em] [&>section]:pt-0 [&>section]:pr-0",
    "[&>section]:pb-0 [&>section]:pl-0 max-w-none pt-8 pr-8 pb-8 pl-8 bg-[#f5f5f3]",
    "rounded-[26px] [&_h1]:text-[32px] [&_h1]:font-normal [@media(max-width:1023px)]:pt-6",
    "[@media(max-width:1023px)]:pr-6 [@media(max-width:1023px)]:pb-6",
    "[@media(max-width:1023px)]:pl-6 [@media(max-width:767px)]:pt-6",
    "[@media(max-width:767px)]:pr-[18px] [@media(max-width:767px)]:pb-6",
    "[@media(max-width:767px)]:pl-[18px] [@media(max-width:767px)]:rounded-[22px]",
    "[@media(max-width:767px)]:[&_h1]:text-[28px]",
  ].join(" "),
  accountOrderDetail: [
    "account-order-detail [&_h1]:tracking-[-.04em] [&>div]:border-[#dededb] [&_h2]:font-medium",
    "max-w-none pt-8 pr-8 pb-8 pl-8 bg-[#f5f5f3] rounded-[26px] [&_h1]:text-[32px]",
    "[&_h1]:font-normal [&>div.border]:[border:0] [&>div.border]:rounded-[20px]",
    "[&>div.border]:bg-white [&>div.grid>div]:[border:0] [&>div.grid>div]:rounded-[20px]",
    "[&>div.grid>div]:bg-white [&>div.border]:pt-6 [&>div.border]:pr-6 [&>div.border]:pb-6",
    "[&>div.border]:pl-6 [@media(max-width:1023px)]:pt-6 [@media(max-width:1023px)]:pr-6",
    "[@media(max-width:1023px)]:pb-6 [@media(max-width:1023px)]:pl-6",
    "[@media(max-width:767px)]:pt-6 [@media(max-width:767px)]:pr-[18px]",
    "[@media(max-width:767px)]:pb-6 [@media(max-width:767px)]:pl-[18px]",
    "[@media(max-width:767px)]:rounded-[22px] [@media(max-width:767px)]:[&_h1]:text-[28px]",
  ].join(" "),
  accountForm: [
    "account-form [&_input:not([type=checkbox])]:[border:1px_solid_#d6d6d2]",
    "[&_input:not([type=checkbox])]:min-h-[50px]",
    "[&_input:focus-visible]:[outline:2px_solid_#2d416f]",
    "[&_input:focus-visible]:[outline-offset:2px] [&_input[type=checkbox]]:w-[18px]",
    "[&_input[type=checkbox]]:h-[18px] [&_input[type=checkbox]]:[accent-color:#2d416f]",
    "[&_button[type=submit]]:min-h-12 [&_label:has(input[type=checkbox])]:pt-4",
    "[&_label:has(input[type=checkbox])]:pr-4 [&_label:has(input[type=checkbox])]:pb-4",
    "[&_label:has(input[type=checkbox])]:pl-4",
    "[@media(max-width:767px)]:[&_.flex.flex-wrap.gap-3>*]:flex-1",
    "[@media(max-width:767px)]:[&_.flex.flex-wrap.gap-3>*]:text-center bg-white rounded-[20px]",
    "mt-7 pt-7 pr-7 pb-7 pl-7 [&_input:not([type=checkbox])]:bg-[#fafafa]",
    "[&_input:not([type=checkbox])]:border-[#e5e5e5]",
    "[&_input:not([type=checkbox])]:rounded-[12px] [&_input:not([type=checkbox]):focus]:bg-white",
    "[&_button[type=submit]]:[background:var(--beecah-black)] [&_button[type=submit]]:pt-[14px]",
    "[&_button[type=submit]]:pr-6 [&_button[type=submit]]:pb-[14px] [&_button[type=submit]]:pl-6",
    "[&_button[type=submit]:hover]:[background:var(--beecah-blue)]",
    "[&_.flex.flex-wrap.gap-3>a]:rounded-[12px] [&_.flex.flex-wrap.gap-3>a]:pt-[14px]",
    "[&_.flex.flex-wrap.gap-3>a]:pr-6 [&_.flex.flex-wrap.gap-3>a]:pb-[14px]",
    "[&_.flex.flex-wrap.gap-3>a]:pl-6 [&_label:has(input[type=checkbox])]:rounded-[12px]",
    "[&_label:has(input[type=checkbox])]:bg-[#f5f5f3]",
    "[&_label:has(input[type=checkbox])]:leading-[1.6] [@media(max-width:767px)]:pt-[22px]",
    "[@media(max-width:767px)]:pr-4 [@media(max-width:767px)]:pb-[22px]",
    "[@media(max-width:767px)]:pl-4",
    "[@media(max-width:767px)]:[&_.flex.flex-wrap.gap-3>*]:[flex-basis:100%]",
  ].join(" "),
  accountNotice: [
    "account-notice pt-4 pr-4 pb-4 pl-4 bg-[#fcf0ed] text-[#913d2e] text-[13px] leading-[1.7]",
    "rounded-[12px]",
  ].join(" "),
  accountSuccess: [
    "account-success pt-4 pr-4 pb-4 pl-4 bg-[#edf4ee] text-[#315d3c] text-[13px] rounded-[12px]",
  ].join(" "),
  accountNavLabel: ["account-nav-label flex-1"].join(" "),
  accountOverview: ["account-overview grid gap-4"].join(" "),
  accountIntroImage: ["account-intro-image absolute inset-0 z-[-2]"].join(" "),
  accountIntroCopy: [
    "account-intro-copy [&>p:last-child]:text-[13px] [&>p:last-child]:leading-[1.7]",
    "[&>p:last-child]:text-[#ffffffd9]",
  ].join(" "),
  accountOrders: ["account-orders bg-white rounded-[20px] overflow-hidden"].join(" "),
} as const satisfies Record<string, string>;
