// Tailwind utilities grouped by component. Keep the marker class for descendant variants.
export const adminStyles = {
  adminDashboard: [
    "admin-dashboard p-5 rounded-10 text-[#1e1e1e] [&_.dash-header]:pt-1 [&_.dash-header]:pr-1",
    "[&_.dash-header]:pb-2 [&_.dash-header]:pl-1 [&_.dash-header_h1]:text-[27px]",
    "[&_.dash-kicker]:text-[9px] [&_.dash-kicker]:text-[#7d7d7d]",
    "[&_.dash-tools_select]:[border:0] [&_.dash-tools_select]:bg-[#ffffffd9]",
    "[&_.dash-tools_select]:rounded-[30px] [&_.dash-tools_button]:[border:0]",
    "[&_.dash-tools_button]:bg-[#ffffffd9] [&_.dash-tools_button]:rounded-[30px]",
    "[&_.dash-tools>a]:rounded-[30px] [&_.dash-tools>a]:bg-[#19191d]",
    "[&_.dash-tools>a]:[border:0] [&_.dash-tabs]:[border:0] [&_.dash-tabs]:gap-[6px]",
    "[&_.dash-tabs]:mt-2 [&_.dash-tabs]:mr-0 [&_.dash-tabs]:mb-4 [&_.dash-tabs]:ml-0",
    "[&_.dash-tabs]:pt-[5px] [&_.dash-tabs]:pr-[5px] [&_.dash-tabs]:pb-[5px]",
    "[&_.dash-tabs]:pl-[5px] [&_.dash-tabs]:bg-[#ffffffb0] [&_.dash-tabs]:rounded-[30px]",
    "[&_.dash-tabs_button]:[border:0] [&_.dash-tabs_button]:pt-[10px]",
    "[&_.dash-tabs_button]:pr-[18px] [&_.dash-tabs_button]:pb-[10px]",
    "[&_.dash-tabs_button]:pl-[18px] [&_.dash-tabs_button]:rounded-[24px]",
    "[&_.dash-tabs_button]:text-[12px] [&_.dash-tabs_button[aria-selected=true]]:bg-[#e7e7e7]",
    "[&_.dash-tabs_button[aria-selected=true]]:text-[#4b4b4b] [&_.dash-tabs>span]:pr-[15px]",
    "[&_.dash-metrics]:gap-3 [&_.dash-metrics_article]:relative",
    "[&_.dash-metrics_article]:[border:0] [&_.dash-metrics_article]:rounded-[22px]",
    "[&_.dash-metrics_article]:bg-[#ffffffdb] [&_.dash-metrics_article]:pt-[19px]",
    "[&_.dash-metrics_article]:pr-[19px] [&_.dash-metrics_article]:pb-[19px]",
    '[&_.dash-metrics_article]:pl-[19px] [&_.dash-metrics_article:before]:content-[""]',
    "[&_.dash-metrics_article:before]:block [&_.dash-metrics_article:before]:w-[22px]",
    "[&_.dash-metrics_article:before]:h-[6px] [&_.dash-metrics_article:before]:rounded-[8px]",
    "[&_.dash-metrics_article:before]:bg-[#bcbcbc] [&_.dash-metrics_article:before]:mb-3",
    "[&_.dash-metrics_article:nth-child(2):before]:bg-[#cdcdcd]",
    "[&_.dash-metrics_article:nth-child(3):before]:bg-[#cecece]",
    "[&_.dash-metrics_article:nth-child(4):before]:bg-[#c5c5c5]",
    "[&_.dash-metrics_strong]:text-[29px] [&_.dash-metrics_strong]:font-medium",
    "[&_.dash-metrics_strong]:mt-[11px] [&_.dash-metrics_strong]:mr-0",
    "[&_.dash-metrics_strong]:mb-[11px] [&_.dash-metrics_strong]:ml-0",
    "[&_.dash-metrics_small]:text-[9px] [&_.dash-metrics_small]:leading-[1.5]",
    "[&_.dash-card]:[border:0] [&_.dash-card]:bg-[#ffffffdb] [&_.dash-card]:rounded-[24px]",
    "[&_.dash-card]:pt-[22px] [&_.dash-card]:pr-[22px] [&_.dash-card]:pb-[22px]",
    "[&_.dash-card]:pl-[22px] [&_.dash-card-title_h2]:text-[14px]",
    "[&_.dash-card-title_svg]:text-[#a6a6a6]",
    "[&_.dash-bar-space]:bg-[repeating-linear-gradient(135deg,#f6f4fa,#f6f4fa_3px,#eeeeee_3px,#eeeeee_5px)]",
    "[&_.dash-bar-space]:rounded-[10px]",
    "[&_.dash-bar-space>div]:bg-[linear-gradient(#c7c7c7,#a8a8a8)]",
    "[&_.dash-bar-space>div]:rounded-[10px] [&_.dash-ranking_li]:pt-[11px]",
    "[&_.dash-ranking_li]:pr-[10px] [&_.dash-ranking_li]:pb-[11px]",
    "[&_.dash-ranking_li]:pl-[10px] [&_.dash-ranking_li]:[border:0]",
    "[&_.dash-ranking_li]:rounded-[13px] [&_.dash-ranking_li]:mt-1 [&_.dash-ranking_li]:mr-0",
    "[&_.dash-ranking_li]:mb-1 [&_.dash-ranking_li]:ml-0 [&_.dash-ranking_li]:bg-[#f7f7fa]",
    "[&_.dash-position]:bg-white [&_.dash-position]:rounded-[10px] [&_.dash-position]:w-[30px]",
    "[&_.dash-position]:h-8 [&_.dash-position]:grid [&_.dash-position]:place-items-center",
    "[&_.dash-position]:text-[#7f7f7f] [&_.dash-position]:shrink-0 [&_.dash-track]:h-[6px]",
    "[&_.dash-track]:rounded-[10px]",
    "[&_.dash-track]:bg-[repeating-linear-gradient(135deg,#e8e8e8,#e8e8e8_2px,#f6f5fa_2px,#f6f5fa_4px)]",
    "[&_.dash-track>span]:bg-[#c0c0c0] [&_.dash-product>a]:text-[12px]",
    "[&_.dash-product>a]:font-medium [&_.dash-ranking_strong]:text-[16px]",
    "[&_.dash-ranking-tabs]:items-center [&_.dash-ranking-tabs]:gap-[6px]",
    "[&_.dash-ranking-tabs]:bg-[#ffffffbc] [&_.dash-ranking-tabs]:pt-2",
    "[&_.dash-ranking-tabs]:pr-2 [&_.dash-ranking-tabs]:pb-2 [&_.dash-ranking-tabs]:pl-2",
    "[&_.dash-ranking-tabs]:rounded-[22px] [&_.dash-ranking-tabs]:mt-0",
    "[&_.dash-ranking-tabs]:mr-0 [&_.dash-ranking-tabs]:mb-4 [&_.dash-ranking-tabs]:ml-0",
    "[&_.dash-ranking-tabs]:flex-wrap [&_.dash-ranking-tabs_button]:rounded-[20px]",
    "[&_.dash-ranking-tabs_button]:bg-transparent [&_.dash-ranking-tabs_button]:text-[11px]",
    "[&_.dash-ranking-tabs_button]:pt-[11px] [&_.dash-ranking-tabs_button]:pr-3",
    "[&_.dash-ranking-tabs_button]:pb-[11px] [&_.dash-ranking-tabs_button]:pl-3",
    "[&_.dash-ranking-tabs_button[aria-pressed=true]]:bg-[#eaeaea]",
    "[&_.dash-ranking-tabs_button[aria-pressed=true]]:text-[#5b5b5b]",
    "[&.ranking-favorites_.dash-ranking-tabs_button[aria-pressed=true]]:bg-[#e6e6e6]",
    "[&.ranking-favorites_.dash-ranking-tabs_button[aria-pressed=true]]:text-[#686868]",
    "[&.ranking-clicks_.dash-ranking-tabs_button[aria-pressed=true]]:bg-[#ebebeb]",
    "[&.ranking-clicks_.dash-ranking-tabs_button[aria-pressed=true]]:text-[#676767]",
    "[&_.dash-panel-1>.dash-grid]:grid-cols-[minmax(0,1.7fr)_minmax(200px,1fr)]",
    "[&_.dash-product-grid]:grid [&_.dash-product-grid]:grid-cols-[repeat(2,minmax(0,1fr))]",
    "[&_.dash-product-grid]:gap-[10px] [&_.dash-product-grid_li]:relative",
    "[&_.dash-product-grid_li]:grid [&_.dash-product-grid_li]:grid-cols-[28px_1fr]",
    "[&_.dash-product-grid_li]:gap-[10px] [&_.dash-product-grid_li]:mt-0",
    "[&_.dash-product-grid_li]:mr-0 [&_.dash-product-grid_li]:mb-0",
    "[&_.dash-product-grid_li]:ml-0 [&_.dash-product-grid_li]:pt-4",
    "[&_.dash-product-grid_li]:pr-4 [&_.dash-product-grid_li]:pb-4",
    "[&_.dash-product-grid_li]:pl-4 [&_.dash-product-grid_li]:bg-[#f6f6f9]",
    "[&_.dash-product-grid_li]:rounded-[17px]",
    "[&_.dash-product-grid_.dash-product]:[grid-column:2]",
    "[&_.dash-product-grid_.dash-product]:min-w-0",
    "[&_.dash-product-grid_.dash-product>a]:[white-space:normal]",
    "[&_.dash-product-grid_.dash-product>a]:[display:-webkit-box]",
    "[&_.dash-product-grid_.dash-product>a]:[-webkit-box-orient:vertical]",
    "[&_.dash-product-grid_.dash-product>a]:[-webkit-line-clamp:2]",
    "[&_.dash-product-grid_.dash-product>a]:min-h-[34px]",
    "[&_.dash-product-grid_.dash-product>a]:leading-[1.4]",
    "[&_.dash-product-grid_strong]:[grid-column:2] [&_.dash-product-grid_strong]:flex",
    "[&_.dash-product-grid_strong]:gap-[6px] [&_.dash-product-grid_strong]:items-baseline",
    "[&_.dash-product-grid_strong]:text-left [&_.dash-product-grid_.dash-track]:mt-3",
    "[&.ranking-favorites_.dash-product-grid_.dash-track>span]:bg-[#bfbfbf]",
    "[&.ranking-clicks_.dash-product-grid_.dash-track>span]:bg-[#c5c5c5]",
    "[&_.dash-blue]:bg-[linear-gradient(145deg,#e7e7e7,#efefef)] [&_.dash-blue]:text-[#434343]",
    "[&_.dash-blue_h2]:text-[23px] [&_.dash-blue_h2]:leading-[1.3]",
    "[&_.dash-blue_.dash-kicker]:text-[#777777] [&_.dash-catalog>div]:border-[#dbdbdb]",
    "[&_.dash-catalog>div]:text-[12px] [&_.dash-stock_li]:bg-[#f7f7fa]",
    "[&_.dash-stock_li]:[border:0] [&_.dash-stock_li]:rounded-[12px]",
    "[&_.dash-stock_li]:pt-[14px] [&_.dash-stock_li]:pr-[14px] [&_.dash-stock_li]:pb-[14px]",
    "[&_.dash-stock_li]:pl-[14px] [&_.dash-stock_li]:mb-2 [&_.dash-stock_li>span]:rounded-[20px]",
    "[&_.dash-stock_li>span]:pt-[6px] [&_.dash-stock_li>span]:pr-[10px]",
    "[&_.dash-stock_li>span]:pb-[6px] [&_.dash-stock_li>span]:pl-[10px]",
    "[&_.dash-stock_li>span]:bg-[#e8e8e8] [&_.dash-stock_li>span.out]:bg-[#e2e2e2]",
    "[&_.dash-stock_li>span.out]:text-[#585858] [&_.dash-panel-2_.dash-catalog>div]:pt-[10px]",
    "[&_.dash-panel-2_.dash-catalog>div]:pr-3 [&_.dash-panel-2_.dash-catalog>div]:pb-[10px]",
    "[&_.dash-panel-2_.dash-catalog>div]:pl-3 [&_.dash-panel-2_.dash-catalog>div]:mb-[6px]",
    "[&_.dash-panel-2_.dash-catalog>div]:[border:0]",
    "[&_.dash-panel-2_.dash-catalog>div]:bg-[#f7f7fa]",
    "[&_.dash-panel-2_.dash-catalog>div]:rounded-[12px]",
    "[&_.dash-panel-2_.dash-catalog>div:first-child]:bg-[#efefef]",
    "[&_.dash-panel-2_.dash-catalog>div:nth-child(2)]:bg-[#f1f1f1]",
    "[&_.dash-panel-2_.dash-catalog>div:nth-child(3)]:bg-[#eaeaea]",
    "[&_.dash-catalog_dd]:text-[20px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_article]:pt-[13px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_article]:pr-4",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_article]:pb-[13px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_article]:pl-4",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_article:before]:mb-2",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_strong]:text-[25px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_strong]:mt-[7px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_strong]:mr-0",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_strong]:mb-[7px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-metrics_strong]:ml-0",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-card]:pt-4",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-card]:pr-4",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-card]:pb-4",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-card]:pl-4",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-chart]:h-35",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-ranking_li]:pt-2",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-ranking_li]:pr-2",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-ranking_li]:pb-2",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-ranking_li]:pl-2",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-tabs]:mb-3",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-product-grid_li]:pt-3",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-product-grid_li]:pr-3",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-product-grid_li]:pb-3",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-product-grid_li]:pl-3",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&_.dash-header_h1]:text-[24px]",
    "[@media(max-width:1100px)]:[&_.dash-panel-1>.dash-grid]:grid-cols-[1fr]",
    "[@media(max-width:1100px)]:[&_.dash-blue_h2]:max-w-none",
    "[@media(max-width:800px)]:[&_.dash-metrics_strong]:text-[23px]",
    "[@media(max-width:800px)]:[&_.dash-metrics_article]:pt-[15px]",
    "[@media(max-width:800px)]:[&_.dash-metrics_article]:pr-[15px]",
    "[@media(max-width:800px)]:[&_.dash-metrics_article]:pb-[15px]",
    "[@media(max-width:800px)]:[&_.dash-metrics_article]:pl-[15px]",
    "[@media(max-width:800px)]:[&_.dash-card]:pt-[18px]",
    "[@media(max-width:800px)]:[&_.dash-card]:pr-[18px]",
    "[@media(max-width:800px)]:[&_.dash-card]:pb-[18px]",
    "[@media(max-width:800px)]:[&_.dash-card]:pl-[18px]",
    "[@media(max-width:800px)]:[&_.dash-tabs_button]:pt-[10px]",
    "[@media(max-width:800px)]:[&_.dash-tabs_button]:pr-3",
    "[@media(max-width:800px)]:[&_.dash-tabs_button]:pb-[10px]",
    "[@media(max-width:800px)]:[&_.dash-tabs_button]:pl-3",
    "[@media(max-width:800px)]:[&_.dash-product-grid]:grid-cols-[1fr_1fr]",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:flex-1",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:justify-center",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:text-[10px]",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:pt-[10px]",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:pr-2",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:pb-[10px]",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button]:pl-2",
    "[@media(max-width:800px)]:[&_.dash-ranking-tabs_button_svg]:w-[13px]",
    "[@media(max-width:800px)]:[&_.dash-header]:pt-2",
    "[@media(max-width:380px)]:[&_.dash-product-grid]:grid-cols-[1fr]",
    "[@media(max-width:380px)]:[&_.dash-tools]:flex-wrap",
  ].join(" "),
  dashHeader: [
    "dash-header flex items-center justify-between gap-4 [&_h1]:text-[30px] [&_h1]:font-medium",
    "[&_h1]:tracking-[-.045em] [&_h1]:mt-[5px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_h1]:text-[26px]",
    "[@media(max-width:1100px)]:flex-wrap",
  ].join(" "),
  dashKicker: ["dash-kicker text-[10px] tracking-[.17em] uppercase text-[#737373]"].join(
    " ",
  ),
  dashTools: [
    "dash-tools flex items-center gap-2 [&_select]:h-[42px]",
    "[&_select]:[border:1px_solid_#e5e5e5] [&_select]:bg-white [&_select]:rounded-[12px]",
    "[&_select]:pt-0 [&_select]:pr-3 [&_select]:pb-0 [&_select]:pl-3 [&_select]:text-[12px]",
    "[&_button]:h-[42px] [&_button]:[border:1px_solid_#e5e5e5] [&_button]:bg-white",
    "[&_button]:rounded-[12px] [&_button]:pt-0 [&_button]:pr-3 [&_button]:pb-0 [&_button]:pl-3",
    "[&_button]:text-[12px] [&>a]:h-[42px] [&>a]:[border:1px_solid_#e5e5e5] [&>a]:rounded-[12px]",
    "[&>a]:pt-0 [&>a]:pr-3 [&>a]:pb-0 [&>a]:pl-3 [&>a]:text-[12px] [&_button]:grid",
    "[&_button]:place-items-center [&>a]:flex [&>a]:items-center [&>a]:bg-[#1e1e1e]",
    "[&>a]:text-white [@media(max-width:600px)]:w-full",
    "[@media(max-width:600px)]:[&_select]:flex-1 [@media(max-width:600px)]:[&_select]:min-w-0",
  ].join(" "),
  dashTabs: [
    "dash-tabs flex items-center gap-5 [border-bottom:1px_solid_#dedede] mt-4 mr-0 mb-4 ml-0",
    "[&_button]:pt-3 [&_button]:pr-0 [&_button]:pb-3 [&_button]:pl-0 [&_button]:text-[13px]",
    "[&_button]:[border-bottom:2px_solid_transparent] [&_button]:text-[#666]",
    "[&_button[aria-selected=true]]:text-[#2d416f]",
    "[&_button[aria-selected=true]]:border-[#2d416f] [&>span]:ml-auto [&>span]:text-[10px]",
    "[&>span]:text-[#777] [@media(max-width:600px)]:gap-4",
    "[@media(max-width:600px)]:[&>span]:hidden",
  ].join(" "),
  dashMetrics: [
    "dash-metrics grid grid-cols-[repeat(4,minmax(0,1fr))] gap-3 mb-4 [&_article]:bg-white",
    "[&_article]:[border:1px_solid_#eee] [&_article]:rounded-[18px] [&_article]:pt-[18px]",
    "[&_article]:pr-[18px] [&_article]:pb-[18px] [&_article]:pl-[18px] [&_p]:text-[11px]",
    "[&_p]:text-[#666] [&_strong]:block [&_strong]:mt-[14px] [&_strong]:mr-0 [&_strong]:mb-2",
    "[&_strong]:ml-0 [&_strong]:text-[clamp(19px,2vw,28px)] [&_strong]:font-medium",
    "[&_strong]:tracking-[-.035em] [&_small]:text-[10px] [&_small]:text-[#777]",
    "[&_small]:leading-[1.5] [&_small]:block",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_article]:pt-[13px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_article]:pr-[13px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_article]:pb-[13px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_article]:pl-[13px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_strong]:mt-2",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_strong]:mr-0",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_strong]:mb-2",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_strong]:ml-0",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_strong]:text-[23px]",
    "[@media(max-width:1100px)]:grid-cols-[repeat(2,minmax(0,1fr))]",
    "[@media(max-width:600px)]:[&_article]:pt-[14px]",
    "[@media(max-width:600px)]:[&_article]:pr-[14px]",
    "[@media(max-width:600px)]:[&_article]:pb-[14px]",
    "[@media(max-width:600px)]:[&_article]:pl-[14px]",
  ].join(" "),
  dashGrid: [
    "dash-grid grid grid-cols-[1.15fr_1fr] gap-4 [@media(max-width:1100px)]:grid-cols-[1fr]",
  ].join(" "),
  dashCard: [
    "dash-card bg-white [border:1px_solid_#eee] rounded-[22px] pt-[22px] pr-[22px] pb-[22px]",
    "pl-[22px] min-w-0 [&_h2]:text-[16px] [&_h2]:font-medium [&_h2]:tracking-[-.02em]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:pt-4",
    "[@media(min-width:1024px)_and_(max-height:800px)]:pr-4",
    "[@media(min-width:1024px)_and_(max-height:800px)]:pb-4",
    "[@media(min-width:1024px)_and_(max-height:800px)]:pl-4 [@media(max-width:600px)]:pt-[18px]",
    "[@media(max-width:600px)]:pr-[18px] [@media(max-width:600px)]:pb-[18px]",
    "[@media(max-width:600px)]:pl-[18px]",
  ].join(" "),
  dashCardTitle: [
    "dash-card-title flex justify-between gap-3 items-start mb-4 [&_p]:text-[10px]",
    "[&_p]:text-[#777] [&_p]:mt-[5px] [&_p]:leading-[1.6] [&>a]:text-[11px]",
    "[&>a]:whitespace-nowrap [&>a]:text-[#2d416f]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:mb-[10px]",
  ].join(" "),
  dashChart: [
    "dash-chart h-[190px] flex gap-2 items-stretch",
    "[@media(min-width:1024px)_and_(max-height:800px)]:h-[145px] [@media(max-width:600px)]:h-45",
  ].join(" "),
  dashBarColumn: [
    "dash-bar-column flex-1 min-w-0 flex flex-col items-center gap-2 [&>span]:text-[9px]",
    "[&>span]:text-[#666] [&>span]:text-center [&>span]:wrap-anywhere [&_small]:text-[10px]",
    "[&_small]:text-[#777]",
  ].join(" "),
  dashBarSpace: [
    "dash-bar-space flex-1 w-[65%] flex items-end bg-[#f7f7f7] rounded-[7px] overflow-hidden",
    "[&>div]:w-full [&>div]:bg-[#2d416f] [&>div]:rounded-[7px_7px_0_0]",
  ].join(" "),
  dashFootnote: ["dash-footnote text-[10px] text-[#777] mt-4 leading-[1.5]"].join(" "),
  dashRanking: [
    "dash-ranking [&_li]:flex [&_li]:items-center [&_li]:gap-3 [&_li]:pt-3 [&_li]:pr-0",
    "[&_li]:pb-3 [&_li]:pl-0 [&_li]:[border-bottom:1px_solid_#f1f1f1]",
    "[&_li:last-child]:[border:0] [&_strong]:text-[15px] [&_strong]:font-medium",
    "[&_strong]:text-right [&_small]:block [&_small]:text-[9px] [&_small]:font-normal",
    "[&_small]:text-[#777] [@media(min-width:1024px)_and_(max-height:800px)]:[&_li]:pt-[9px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_li]:pr-0",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_li]:pb-[9px]",
    "[@media(min-width:1024px)_and_(max-height:800px)]:[&_li]:pl-0",
  ].join(" "),
  dashPosition: ["dash-position text-[11px] text-[#999]"].join(" "),
  dashProduct: [
    "dash-product min-w-0 flex-1 text-[12px] [&>a]:block [&>a]:overflow-hidden",
    "[&>a]:whitespace-nowrap [&>a]:text-ellipsis",
  ].join(" "),
  dashTrack: [
    "dash-track block h-[3px] bg-[#f3f3f3] mt-[9px] rounded-[4px] [&>span]:block [&>span]:h-full",
    "[&>span]:bg-[#b3b3b3] [&>span]:rounded-[4px]",
  ].join(" "),
  dashEmpty: [
    "dash-empty min-h-[210px] flex flex-col items-center justify-center gap-[14px] text-[#777]",
    "text-center text-[12px] leading-[1.8] pt-5 pr-5 pb-5 pl-5 [&_strong]:text-[#333]",
    "[&_strong]:font-medium",
  ].join(" "),
  dashRankingTabs: [
    "dash-ranking-tabs flex gap-2 mt-5 mr-0 mb-5 ml-0 [&_button]:flex [&_button]:items-center",
    "[&_button]:gap-2 [&_button]:bg-white [&_button]:rounded-[12px] [&_button]:pt-3",
    "[&_button]:pr-3 [&_button]:pb-3 [&_button]:pl-3 [&_button]:text-[12px]",
    "[&_button[aria-pressed=true]]:bg-[#1e1e1e] [&_button[aria-pressed=true]]:text-white",
    "[@media(max-width:600px)]:gap-[6px] [@media(max-width:600px)]:flex-wrap",
    "[@media(max-width:600px)]:[&_button]:text-[11px]",
    "[@media(max-width:600px)]:[&_button]:pt-[10px]",
    "[@media(max-width:600px)]:[&_button]:pr-[10px]",
    "[@media(max-width:600px)]:[&_button]:pb-[10px]",
    "[@media(max-width:600px)]:[&_button]:pl-[10px]",
  ].join(" "),
  dashBlue: [
    "dash-blue bg-[#2d416f] text-white [border:0] [&_.dash-kicker]:text-[#ffffff99]",
    "[&_h2]:text-[24px] [&_h2]:max-w-60 [&_h2]:mt-5 [&_h2]:mr-0 [&_h2]:mb-5 [&_h2]:ml-0",
    "[&>a]:flex [&>a]:justify-between [&>a]:mt-[22px] [&>a]:text-[12px]",
  ].join(" "),
  dashCatalog: [
    "dash-catalog [&>div]:flex [&>div]:justify-between [&>div]:items-center [&>div]:pt-[11px]",
    "[&>div]:pr-0 [&>div]:pb-[11px] [&>div]:pl-0 [&>div]:[border-bottom:1px_solid_#8882]",
    "[&>div]:text-[12px] [&_dd]:text-[19px] [&_dd]:font-medium",
  ].join(" "),
  dashStock: [
    "dash-stock [&_li]:flex [&_li]:justify-between [&_li]:items-center [&_li]:gap-3",
    "[&_li]:pt-[17px] [&_li]:pr-0 [&_li]:pb-[17px] [&_li]:pl-0",
    "[&_li]:[border-bottom:1px_solid_#eee] [&_li]:text-[12px] [&_li>a]:min-w-0",
    "[&_li>a]:overflow-hidden [&_li>a]:whitespace-nowrap [&_li>a]:text-ellipsis",
    "[&_li>span]:whitespace-nowrap [&_li>span]:bg-[#f5f5f5] [&_li>span]:text-[#646464]",
    "[&_li>span]:pt-[5px] [&_li>span]:pr-2 [&_li>span]:pb-[5px] [&_li>span]:pl-2",
    "[&_li>span]:rounded-[7px] [&_li>span]:text-[10px] [&_li>span.out]:bg-[#f3f3f3]",
    "[&_li>span.out]:text-[#555555]",
  ].join(" "),
  dashLink: ["dash-link block mt-[18px] text-[12px] text-[#2d416f]"].join(" "),
  dashWarning: [
    "dash-warning bg-[#f5f5f5] text-[#5b5b5b] pt-[10px] pr-[14px] pb-[10px] pl-[14px]",
    "rounded-[12px] text-[12px] mb-3",
  ].join(" "),
  adminTopbar: [
    "admin-topbar [border-bottom:1px_solid_#fff9] [&>div]:max-w-none [&>div]:pt-[18px]",
    "[&>div]:pr-3 [&>div]:pb-[18px] [&>div]:pl-3",
    "[&>div>div:first-child_p:first-child]:text-[16px]",
    "[&>div>div:first-child_p:first-child]:font-[650]",
    "[&>div>div:first-child_p:first-child]:normal-case",
    "[&>div>div:first-child_p:first-child]:tracking-[-.04em]",
    "[&>div>div:first-child_p:first-child]:text-[#222]",
    "[&>div>div:first-child_p:last-child]:text-[11px]",
    "[&>div>div:first-child_p:last-child]:font-normal",
    "[&>div>div:first-child_p:last-child]:text-[#777] [&>div>div:last-child]:flex",
    "[&>div>div:last-child]:items-center [&>div>div:last-child]:gap-5 [&_a]:bg-white",
    "[&_a]:pt-[10px] [&_a]:pr-4 [&_a]:pb-[10px] [&_a]:pl-4 [&_a]:rounded-[30px]",
    "[&_a]:no-underline [&_a]:text-[#373737]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&>div]:pt-[10px]",
    "[@media(min-width:1101px)_and_(max-height:800px)]:[&>div]:pb-[10px]",
    "[@media(max-width:800px)]:[&>div]:pt-[14px] [@media(max-width:800px)]:[&>div]:pr-1",
    "[@media(max-width:800px)]:[&>div]:pb-[14px] [@media(max-width:800px)]:[&>div]:pl-1",
    "[@media(max-width:800px)]:[&>div>div:last-child]:gap-2",
    "[@media(max-width:800px)]:[&>div>div:last-child>p]:max-w-40",
    "[@media(max-width:800px)]:[&>div>div:last-child>p]:text-[10px]",
    "[@media(max-width:380px)]:[&>div>div:last-child>p]:hidden mt-0 mr-0 mb-0 ml-0 grid",
    "grid-cols-[190px_minmax(200px,1fr)_auto] items-center gap-6 [border:0] min-h-22 max-w-400",
    "mx-auto [&>a.admin-brand]:text-[27px] [&>a.admin-brand]:tracking-[-.06em]",
    "[&>a.admin-brand]:font-semibold [&>a.admin-brand]:text-[#242424]",
    "[&>a.admin-brand]:no-underline [&_.admin-account]:flex [&_.admin-account]:items-center",
    "[&_.admin-account]:gap-[10px] [&_.admin-account]:pt-0 [&_.admin-account]:pr-0",
    "[&_.admin-account]:pb-0 [&_.admin-account]:pl-0 [&_.admin-account>a]:text-[11px]",
    "[&_.admin-account>a]:pt-[10px] [&_.admin-account>a]:pr-3 [&_.admin-account>a]:pb-[10px]",
    "[&_.admin-account>a]:pl-3 [&_.admin-account>a]:bg-white [&_.admin-account>a]:rounded-[25px]",
    "[&_.admin-account>a]:whitespace-nowrap",
    "[@media(max-width:1100px)]:grid-cols-[160px_minmax(200px,1fr)_auto]",
    "[@media(max-width:1100px)]:gap-3 [@media(max-width:800px)]:grid-cols-[1fr_auto]",
    "[@media(max-width:800px)]:gap-3 [@media(max-width:800px)]:pt-4",
    "[@media(max-width:800px)]:pr-0 [@media(max-width:800px)]:pb-4",
    "[@media(max-width:800px)]:pl-0 [@media(max-width:800px)]:min-h-auto",
    "[@media(max-width:800px)]:[&>a.admin-brand]:text-[24px] [&>.admin-search]:pt-0",
    "[&>.admin-search]:pr-0 [&>.admin-search]:pb-0 [&>.admin-search]:pl-0",
    "[&>.admin-search]:max-w-none [&>.admin-search>.admin-search-results]:block",
    "[&>.admin-search>.admin-search-results]:text-left",
    "[&>.admin-search>.admin-search-field]:gap-[10px]",
    "[&>.admin-search>.admin-search-results_p]:font-normal",
    "[&>.admin-search>.admin-search-results_p]:normal-case",
    "[&>.admin-search>.admin-search-results_p]:tracking-[normal] [&>a.admin-brand]:flex",
    "[&>a.admin-brand]:flex-col [&>a.admin-brand]:items-center [&>a.admin-brand]:justify-center",
    "[&>a.admin-brand]:w-35 [&>a.admin-brand]:pt-1 [&>a.admin-brand]:pr-2 [&>a.admin-brand]:pb-1",
    "[&>a.admin-brand]:pl-2 [&>a.admin-brand]:bg-white [&>a.admin-brand]:rounded-[12px]",
    "[&>a.admin-brand]:leading-[1] [@media(max-width:800px)]:[&>a.admin-brand]:w-[110px]",
    "[@media(max-width:800px)]:[&>a.admin-brand]:pt-0",
    "[@media(max-width:800px)]:[&>a.admin-brand]:pr-[6px]",
    "[@media(max-width:800px)]:[&>a.admin-brand]:pb-0",
    "[@media(max-width:800px)]:[&>a.admin-brand]:pl-[6px]",
  ].join(" "),
  adminFrame: [
    "admin-frame grid grid-cols-[190px_minmax(0,1fr)] gap-5 max-w-400 mt-auto mr-auto mb-auto",
    "ml-auto pr-0 pb-0 pl-0 [@media(max-width:1100px)]:grid-cols-[160px_minmax(0,1fr)]",
    "[@media(max-width:1100px)]:gap-3 [@media(max-width:800px)]:block pt-0",
  ].join(" "),
  adminSidebar: [
    "admin-sidebar self-start sticky top-6 [&_nav]:gap-2 [&_nav_a]:text-[12px]",
    "[&_nav_a]:pt-[13px] [&_nav_a]:pr-[15px] [&_nav_a]:pb-[13px] [&_nav_a]:pl-[15px]",
    "[&_nav_a]:rounded-[25px] [&_nav_a_svg]:w-4 [&_nav_a_svg]:text-[#969696]",
    "[&_nav_a[aria-current=page]_svg]:text-[#5b5b5b] [@media(max-width:1100px)]:[&_nav_a]:pt-3",
    "[@media(max-width:1100px)]:[&_nav_a]:pr-3 [@media(max-width:1100px)]:[&_nav_a]:pb-3",
    "[@media(max-width:1100px)]:[&_nav_a]:pl-3 [@media(max-width:1100px)]:[&_nav_a]:text-[11px]",
    "[@media(max-width:800px)]:static [@media(max-width:800px)]:[&_nav]:flex-row",
    "[@media(max-width:800px)]:[&_nav]:overflow-auto [@media(max-width:800px)]:[&_nav]:gap-[5px]",
    "[@media(max-width:800px)]:[&_nav_a]:shrink-0 min-h-[calc(100dvh_-_125px)] bg-[#ffffff45]",
    "rounded-[20px] pt-[18px] pr-[6px] pb-[18px] pl-[6px] [@media(max-width:800px)]:min-h-0",
    "[@media(max-width:800px)]:[background:none] [@media(max-width:800px)]:pt-0",
    "[@media(max-width:800px)]:pr-0 [@media(max-width:800px)]:pb-4",
    "[@media(max-width:800px)]:pl-0 [@media(max-width:800px)]:rounded-none",
    "[&_nav_a[aria-current=page]]:bg-white [&_nav_a[aria-current=page]]:text-[#1e1e1e]",
    "[&_nav_a[aria-current=page]]:shadow-[inset_3px_0_#2d416f]",
  ].join(" "),
  adminMain: [
    "admin-main min-w-0 pt-1 pr-0 pb-0 pl-0 [&>section:not(.admin-dashboard)]:pt-[22px]!",
    "[&>section:not(.admin-dashboard)]:pr-[22px]! [&>section:not(.admin-dashboard)]:pb-[22px]!",
    "[&>section:not(.admin-dashboard)]:pl-[22px]! [&>section:not(.admin-dashboard)]:max-w-none",
    "[&>section:not(.admin-dashboard)]:bg-[#ffffffb8]",
    "[&>section:not(.admin-dashboard)]:rounded-[24px] [&_h1]:tracking-[-.04em]",
    "[&_h1]:font-medium [&_form]:rounded-[20px] [&_form]:border-[#ebebeb]",
    "[&_input:not([type=radio]):not([type=checkbox])]:rounded-[12px]",
    "[&_input:not([type=radio]):not([type=checkbox])]:border-[#e8e8e8]",
    "[&_input:not([type=radio]):not([type=checkbox])]:min-h-[42px] [&_select]:rounded-[12px]",
    "[&_select]:border-[#e8e8e8] [&_select]:min-h-[42px] [&_textarea]:rounded-[12px]",
    "[&_textarea]:border-[#e8e8e8] [&_textarea]:min-h-[42px]",
    "[&_button]:[transition:background_.18s,color_.18s,box-shadow_.18s]",
    "[&_a]:[transition:background_.18s,color_.18s,box-shadow_.18s]",
    "[&_button:focus-visible]:[outline:2px_solid_#6e6e6e]",
    "[&_button:focus-visible]:[outline-offset:3px]",
    "[&_a:focus-visible]:[outline:2px_solid_#6e6e6e] [&_a:focus-visible]:[outline-offset:3px]",
    "[&_input:focus-visible]:[outline:2px_solid_#6e6e6e]",
    "[&_input:focus-visible]:[outline-offset:3px]",
    "[&_select:focus-visible]:[outline:2px_solid_#6e6e6e]",
    "[&_select:focus-visible]:[outline-offset:3px] [&_table]:bg-white [&_table]:w-full",
    "[&_table_th]:bg-[#f6f5f9] [&_table_th]:text-[#737373] [&_table_th]:text-[10px]",
    "[&_table_th]:uppercase [&_table_th]:tracking-[.08em] [&_table_th]:whitespace-nowrap",
    "[&_table_td]:text-[12px] [&_table_td]:border-[#f1eff5]",
    "[&_table_tbody_tr:hover]:bg-[#faf9ff] [&_table_td_a]:inline-flex",
    "[&_table_td_a]:items-center [&_table_td_a]:min-h-9 [&_table_td_a]:pt-1",
    "[&_table_td_a]:pr-[10px] [&_table_td_a]:pb-1 [&_table_td_a]:pl-[10px]",
    "[&_table_td_a]:rounded-[20px] [&_table_td_a]:bg-[#f0f0f0] [&_table_td_a]:no-underline",
    "[&_table_td_a]:text-[11px] [&_table_td_a]:text-[#5b5b5b]",
    "[&_.overflow-x-auto]:rounded-[18px] [&_.overflow-x-auto]:border-[#efedf4]",
    "[&_.text-green-700]:text-[#626262] [&_.text-green-600]:text-[#626262]",
    "[&_.text-amber-600]:text-[#666666] [&_.text-red-600]:text-[#5e5e5e]",
    "[&_article]:rounded-[20px] [&_article]:overflow-hidden",
    "[&_form_button[type=submit]]:rounded-[24px] [&_section>div.border]:rounded-[20px]",
    "[&_section>div.border]:overflow-hidden",
    "[@media(max-width:800px)]:[&>section:not(.admin-dashboard)]:pt-4!",
    "[@media(max-width:800px)]:[&>section:not(.admin-dashboard)]:pr-4!",
    "[@media(max-width:800px)]:[&>section:not(.admin-dashboard)]:pb-4!",
    "[@media(max-width:800px)]:[&>section:not(.admin-dashboard)]:pl-4!",
  ].join(" "),
  dashSearch: [
    "dash-search mr-auto flex-1 min-w-[150px] max-w-[230px] [&_input]:w-full [&_input]:pt-[10px]",
    "[&_input]:pr-[14px] [&_input]:pb-[10px] [&_input]:pl-[14px] [&_input]:bg-[#f5f5f8]",
    "[&_input]:text-[12px] [&_input]:[border:0] [&_input]:rounded-[22px]!",
    "[@media(max-width:800px)]:max-w-none [@media(max-width:800px)]:[flex-basis:100%]",
  ].join(" "),
  adminWorkspace: [
    "admin-workspace [@media(max-width:1100px)]:[border-width:5px] [border:0] rounded-none pt-0",
    "pr-6 pb-6 pl-6 min-h-[100dvh] [@media(max-width:1100px)]:pt-0",
    "[@media(max-width:1100px)]:pr-4 [@media(max-width:1100px)]:pb-5",
    "[@media(max-width:1100px)]:pl-4 [--admin-purple:#2d416f] [--admin-purple-ink:#2d416f]",
    "[--admin-green:#ededed] [--admin-pink:#f3f3f3] bg-[#f5f5f5] text-[#1e1e1e]",
    "[&_svg]:text-[#1e1e1e]! [&_.dash-tabs_button[aria-selected=true]]:bg-[#e5e7ec]",
    "[&_.dash-tabs_button[aria-selected=true]]:text-[#1e1e1e]",
    "[&_.dash-ranking-tabs_button[aria-pressed=true]]:bg-[#e5e7ec]",
    "[&_.dash-ranking-tabs_button[aria-pressed=true]]:text-[#1e1e1e]",
    "[&_.dash-bar-space>div]:bg-[#2d416f] [&_.dash-track>span]:bg-[#2d416f]",
    "[&_.dash-product-grid_.dash-track>span]:bg-[#2d416f]",
    "[&_.dash-metrics_article:before]:bg-[#2d416f]",
    "[&_.dash-metrics_article:nth-child(2):before]:bg-[#1e1e1e]",
    "[&_.dash-metrics_article:nth-child(3):before]:bg-[#777]",
    "[&_.dash-metrics_article:nth-child(4):before]:bg-[#bbb] [&_.dash-blue]:bg-[#eceef2]",
    "[&_.dash-blue]:text-[#1e1e1e] [&_.dash-blue_.dash-kicker]:text-[#606775]",
    "[&_.dash-stock_li>span]:bg-[#e7e7e7] [&_.dash-stock_li>span]:text-[#444]",
    "[&_.customer-status]:bg-[#e7e7e7] [&_.customer-status]:text-[#444]",
    "[&_.dash-stock_li>span.out]:bg-[#1e1e1e] [&_.dash-stock_li>span.out]:text-white",
    "[&_.customer-status.confirmed]:bg-[#e4e8ef] [&_.customer-status.confirmed]:text-[#2d416f]",
    "[&_.customer-metrics_article]:bg-white",
    "[&_.customer-metrics_article]:[border-top:3px_solid_#2d416f]",
    "[&_.customer-metrics_article:nth-child(2)]:border-[#1e1e1e]",
    "[&_.customer-metrics_article:nth-child(3)]:border-[#999]",
    '[&_[class*="text-violet-"]]:text-[#2d416f] [&_[class*="text-purple-"]]:text-[#2d416f]',
    '[&_[class*="text-pink-"]]:text-[#2d416f] [&_[class*="text-rose-"]]:text-[#2d416f]',
    '[&_[class*="text-green-"]]:text-[#2d416f] [&_[class*="text-red-"]]:text-[#2d416f]',
    '[&_[class*="text-amber-"]]:text-[#2d416f] [&_[class*="text-blue-"]]:text-[#2d416f]',
    '[&_[class*="bg-violet-"]]:bg-[#eef0f4] [&_[class*="bg-purple-"]]:bg-[#eef0f4]',
    '[&_[class*="bg-pink-"]]:bg-[#eef0f4] [&_[class*="bg-rose-"]]:bg-[#eef0f4]',
    '[&_[class*="bg-green-"]]:bg-[#eef0f4] [&_[class*="bg-red-"]]:bg-[#eef0f4]',
    '[&_[class*="bg-amber-"]]:bg-[#eef0f4] [&_[class*="bg-blue-"]]:bg-[#eef0f4]',
    "[&_[role=alert]]:text-[#1e1e1e] [&_[role=alert]]:bg-[#eee]",
    "[&_[role=alert]]:[border-left:3px_solid_#1e1e1e] [&_input]:[accent-color:#2d416f]",
    "[&_select]:[accent-color:#2d416f] [&_:focus-visible]:[outline-color:#2d416f]",
    "[&_.admin-search-results_section>a:hover]:bg-[#eee] [&.admin-dark]:scheme-dark",
    "[&.admin-dark]:bg-black [&.admin-dark]:text-[#eeeeef]",
    "[&.admin-dark]:[--beecah-black:#eeeeef] [&.admin-dark]:[--beecah-blue:#2d416f]",
    "[&.admin-dark]:min-h-[100dvh] [&.admin-dark_.admin-topbar]:bg-transparent",
    "[&.admin-dark_.admin-frame]:bg-transparent",
    "[&.admin-dark_.admin-topbar>a.admin-brand]:bg-transparent",
    "[&.admin-dark_.admin-brand_img]:[filter:invert(1)]",
    "[&.admin-dark_.admin-brand_img]:[mix-blend-mode:screen]",
    "[&.admin-dark_.admin-brand>span]:text-[#b7b9c0]",
    "[&.admin-dark_.admin-account-avatar]:bg-[#292d35]",
    "[&.admin-dark_.admin-account-avatar]:text-[#f1f1f3]",
    "[&.admin-dark_.customer-avatar]:bg-[#292d35] [&.admin-dark_.customer-avatar]:text-[#f1f1f3]",
    "[&.admin-dark_.admin-account_strong]:text-[#f1f1f3]",
    "[&.admin-dark_.admin-account>div>span]:text-[#a8abb4]",
    "[&.admin-dark_.admin-topbar_.admin-account>a]:bg-[#25282e]",
    "[&.admin-dark_.admin-topbar_.admin-account>a]:text-[#f1f1f3]",
    "[&.admin-dark_.admin-sidebar_nav_a]:text-[#b9bdc7]",
    "[&.admin-dark_.admin-sidebar_nav_a:hover]:bg-[#24272e]",
    "[&.admin-dark_.admin-sidebar_nav_a:hover]:text-white",
    "[&.admin-dark_.admin-sidebar_nav_a[aria-current=page]]:text-white",
    "[&.admin-dark_svg]:text-[#e6e8ed]!",
    "[&.admin-dark_.admin-main>section:not(.admin-dashboard)]:bg-[#181a1f]",
    "[&.admin-dark_.admin-dashboard]:text-[#eee]",
    "[&.admin-dark_.dash-metrics_article]:bg-[#1c1f25]",
    "[&.admin-dark_.dash-metrics_article]:[border:1px_solid_#2d3038]",
    "[&.admin-dark_.dash-metrics_article]:text-[#eee] [&.admin-dark_.dash-card]:bg-[#1c1f25]",
    "[&.admin-dark_.dash-card]:[border:1px_solid_#2d3038] [&.admin-dark_.dash-card]:text-[#eee]",
    "[&.admin-dark_.customer-metrics_article]:bg-[#1c1f25]",
    "[&.admin-dark_.customer-metrics_article]:[border:1px_solid_#2d3038]",
    "[&.admin-dark_.customer-metrics_article]:text-[#eee]",
    "[&.admin-dark_.dash-kicker]:text-[#aeb3bf] [&.admin-dark_.dash-metrics_p]:text-[#aeb3bf]",
    "[&.admin-dark_.dash-metrics_small]:text-[#aeb3bf]",
    "[&.admin-dark_.dash-card-title_p]:text-[#aeb3bf]",
    "[&.admin-dark_.dash-footnote]:text-[#aeb3bf]",
    "[&.admin-dark_.dash-bar-column>span]:text-[#aeb3bf]",
    "[&.admin-dark_.dash-bar-column_small]:text-[#aeb3bf]",
    "[&.admin-dark_.dash-ranking_small]:text-[#aeb3bf] [&.admin-dark_.dash-empty]:text-[#aeb3bf]",
    "[&.admin-dark_.customer-metrics_p]:text-[#aeb3bf]",
    "[&.admin-dark_.customer-role]:text-[#aeb3bf] [&.admin-dark_.dash-empty_strong]:text-[#eee]",
    "[&.admin-dark_.dash-tools_select]:bg-[#242831]",
    "[&.admin-dark_.dash-tools_select]:text-[#eee]",
    "[&.admin-dark_.dash-tools_select]:[border:1px_solid_#353a46]",
    "[&.admin-dark_.dash-tools_button]:bg-[#242831]",
    "[&.admin-dark_.dash-tools_button]:text-[#eee]",
    "[&.admin-dark_.dash-tools_button]:[border:1px_solid_#353a46]",
    "[&.admin-dark_.dash-tools>a]:text-[#eee]",
    "[&.admin-dark_.dash-tools>a]:[border:1px_solid_#353a46]",
    "[&.admin-dark_.dash-tools>a]:bg-[#2d416f] [&.admin-dark_.dash-tabs]:bg-[#1b1e24]",
    "[&.admin-dark_.dash-ranking-tabs]:bg-[#1b1e24]",
    "[&.admin-dark_.dash-tabs_button]:bg-transparent",
    "[&.admin-dark_.dash-tabs_button]:text-[#b7bdc9]",
    "[&.admin-dark_.dash-ranking-tabs_button]:bg-transparent",
    "[&.admin-dark_.dash-ranking-tabs_button]:text-[#b7bdc9]",
    "[&.admin-dark_.dash-tabs_button[aria-selected=true]]:bg-[#2d416f]",
    "[&.admin-dark_.dash-tabs_button[aria-selected=true]]:text-white",
    "[&.admin-dark_.dash-ranking-tabs_button[aria-pressed=true]]:bg-[#2d416f]",
    "[&.admin-dark_.dash-ranking-tabs_button[aria-pressed=true]]:text-white",
    "[&.admin-dark_.dash-tabs>span]:text-[#a6acb9] [&.admin-dark_.dash-ranking_li]:bg-[#242830]",
    "[&.admin-dark_.dash-ranking_li]:text-[#eee]",
    "[&.admin-dark_.dash-ranking_li]:border-[#353943]",
    "[&.admin-dark_.dash-product-grid_li]:bg-[#242830]",
    "[&.admin-dark_.dash-product-grid_li]:text-[#eee]",
    "[&.admin-dark_.dash-product-grid_li]:border-[#353943]",
    "[&.admin-dark_.dash-stock_li]:bg-[#242830] [&.admin-dark_.dash-stock_li]:text-[#eee]",
    "[&.admin-dark_.dash-stock_li]:border-[#353943]",
    "[&.admin-dark_.dash-panel-2_.dash-catalog>div]:bg-[#242830]",
    "[&.admin-dark_.dash-panel-2_.dash-catalog>div]:text-[#eee]",
    "[&.admin-dark_.dash-panel-2_.dash-catalog>div]:border-[#353943]",
    "[&.admin-dark_.dash-position]:bg-[#333945] [&.admin-dark_.dash-position]:text-[#d9deea]",
    "[&.admin-dark_.dash-bar-space]:bg-[repeating-linear-gradient(135deg,#252932,#252932_3px,#2d323d_3px,#2d323d_5px)]",
    "[&.admin-dark_.dash-track]:bg-[repeating-linear-gradient(135deg,#252932,#252932_3px,#2d323d_3px,#2d323d_5px)]",
    "[&.admin-dark_.dash-bar-space>div]:bg-[#718ab8]",
    "[&.admin-dark_.dash-track>span]:bg-[#718ab8]",
    "[&.admin-dark_.dash-product-grid_.dash-track>span]:bg-[#718ab8]",
    "[&.admin-dark_.dash-blue]:bg-[#1e2b46] [&.admin-dark_.dash-blue]:text-[#f1f3f7]",
    "[&.admin-dark_.dash-blue_.dash-kicker]:text-[#b9c5dc]",
    "[&.admin-dark_.dash-catalog>div]:border-[#3a4354]",
    "[&.admin-dark_.dash-card-title>a]:text-[#c3d2f0] [&.admin-dark_.dash-link]:text-[#c3d2f0]",
    "[&.admin-dark_.admin-main_table_td_a]:text-[#c3d2f0]",
    "[&.admin-dark_.dash-stock_li>span]:bg-[#383e49]",
    "[&.admin-dark_.dash-stock_li>span]:text-[#e5e8ed]",
    "[&.admin-dark_.customer-status]:bg-[#383e49] [&.admin-dark_.customer-status]:text-[#e5e8ed]",
    "[&.admin-dark_.dash-stock_li>span.out]:bg-[#e1e3e8]",
    "[&.admin-dark_.dash-stock_li>span.out]:text-[#17191f]",
    "[&.admin-dark_.customer-status.confirmed]:bg-[#2d416f]",
    "[&.admin-dark_.customer-status.confirmed]:text-white",
    "[&.admin-dark_.customer-filter]:bg-[#252931] [&.admin-dark_.customer-filter]:text-[#eee]",
    "[&.admin-dark_.dash-search_input]:bg-[#252931]",
    "[&.admin-dark_.dash-search_input]:text-[#eee] [&.admin-dark_.admin-main_table]:bg-[#1d2026]",
    "[&.admin-dark_.admin-main_table]:text-[#eee]",
    "[&.admin-dark_.admin-main_table_th]:bg-[#282c34]",
    "[&.admin-dark_.admin-main_table_th]:text-[#c1c6d1]",
    "[&.admin-dark_.admin-main_table_td]:border-[#343841]",
    "[&.admin-dark_.admin-main_table_tr]:border-[#343841]",
    "[&.admin-dark_.admin-main_table_tbody_tr:hover]:bg-[#282d37]",
    "[&.admin-dark_.admin-main_table_td_a]:bg-[#2a354d]",
    "[&.admin-dark_.admin-search-field]:bg-[#20232a]",
    "[&.admin-dark_.admin-search-field]:text-[#eee]",
    "[&.admin-dark_.admin-search-field]:border-[#363b46]",
    "[&.admin-dark_.admin-search-results]:bg-[#20232a]",
    "[&.admin-dark_.admin-search-results]:text-[#eee]",
    "[&.admin-dark_.admin-search-results]:border-[#363b46]",
    "[&.admin-dark_.admin-search-field_input]:text-[#eee]",
    "[&.admin-dark_.admin-search-field_kbd]:bg-[#333843]",
    "[&.admin-dark_.admin-search-field_kbd]:text-[#c8ceda]",
    "[&.admin-dark_.admin-search-results_h2]:text-[#e6eaf2]",
    "[&.admin-dark_.admin-search-results_strong]:text-[#e6eaf2]",
    "[&.admin-dark_.search-caption]:text-[#acb3c1] [&.admin-dark_.search-message]:text-[#acb3c1]",
    "[&.admin-dark_.admin-search-results_small]:text-[#acb3c1]",
    "[&.admin-dark_.admin-search-results_h2>span]:text-[#acb3c1]",
    "[&.admin-dark_.admin-search-results_section>a:hover]:bg-[#303a50]",
    "[&.admin-dark_.admin-search-results_section>a:focus-visible]:bg-[#303a50]",
    '[&.admin-dark_.admin-main_[class*="bg-white"]]:bg-[#23272f]',
    '[&.admin-dark_.admin-main_[class*="bg-neutral-50"]]:bg-[#23272f]',
    '[&.admin-dark_.admin-main_[class*="bg-neutral-100"]]:bg-[#23272f]',
    '[&.admin-dark_.admin-main_[class*="bg-neutral-200"]]:bg-[#343944]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-950"]]:text-[#e3e6ee]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-900"]]:text-[#e3e6ee]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-800"]]:text-[#e3e6ee]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-700"]]:text-[#e3e6ee]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-600"]]:text-[#abb2c0]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-500"]]:text-[#abb2c0]',
    '[&.admin-dark_.admin-main_[class*="text-neutral-400"]]:text-[#abb2c0]',
    '[&.admin-dark_.admin-main_[class*="border-neutral-"]]:border-[#393e49]',
    "[&.admin-dark_.admin-main_form]:border-[#393e49]",
    "[&.admin-dark_.admin-main_.overflow-x-auto]:border-[#393e49]",
    "[&.admin-dark_.admin-main_input:not([type=checkbox]):not([type=radio]):not([type=file])]:bg-[#15181e]",
    "[&.admin-dark_.admin-main_input:not([type=checkbox]):not([type=radio]):not([type=file])]:text-[#eee]",
    "[&.admin-dark_.admin-main_input:not([type=checkbox]):not([type=radio]):not([type=file])]:border-[#404654]",
    "[&.admin-dark_.admin-main_select]:bg-[#15181e]",
    "[&.admin-dark_.admin-main_select]:text-[#eee]",
    "[&.admin-dark_.admin-main_select]:border-[#404654]",
    "[&.admin-dark_.admin-main_textarea]:bg-[#15181e]",
    "[&.admin-dark_.admin-main_textarea]:text-[#eee]",
    "[&.admin-dark_.admin-main_textarea]:border-[#404654]",
    "[&.admin-dark_input::placeholder]:text-[#929ba9]",
    "[&.admin-dark_textarea::placeholder]:text-[#929ba9]",
    '[&.admin-dark_.admin-main_button[class*="bg-neutral-950"]]:bg-[#2d416f]',
    '[&.admin-dark_.admin-main_button[class*="bg-neutral-950"]]:text-white',
    '[&.admin-dark_.admin-main_a[class*="bg-neutral-950"]]:bg-[#2d416f]',
    '[&.admin-dark_.admin-main_a[class*="bg-neutral-950"]]:text-white',
    '[&.admin-dark_.admin-main_button[class*="bg-neutral-950"]:hover]:bg-[#3b5487]',
    '[&.admin-dark_.admin-main_a[class*="bg-neutral-950"]:hover]:bg-[#3b5487]',
    '[&.admin-dark_[class*="text-violet-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-purple-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-pink-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-rose-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-green-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-red-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-amber-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="text-blue-"]]:text-[#c2d0ea]',
    '[&.admin-dark_[class*="bg-violet-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-purple-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-pink-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-rose-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-green-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-red-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-amber-"]]:bg-[#293447]',
    '[&.admin-dark_[class*="bg-blue-"]]:bg-[#293447] [&.admin-dark_[role=alert]]:bg-[#303642]',
    "[&.admin-dark_[role=alert]]:text-[#f1f1f4] [&.admin-dark_[role=alert]]:border-[#b6c6e3]",
    "[&.admin-dark_.dash-warning]:bg-[#303642] [&.admin-dark_.dash-warning]:text-[#f1f1f4]",
    "[&.admin-dark_.dash-warning]:border-[#b6c6e3]",
    "[&.admin-dark_:focus-visible]:[outline:2px_solid_#b1c6f0]",
    "[&.admin-dark_:focus-visible]:[outline-offset:3px] [&.admin-dark_.admin-sidebar]:bg-[#111]",
    "[&.admin-dark_.admin-dashboard_.dash-card]:bg-[#171717]",
    "[&.admin-dark_.admin-dashboard_.dash-card]:[border:0]",
    "[&.admin-dark_.admin-dashboard_.dash-metrics_article]:bg-[#171717]",
    "[&.admin-dark_.admin-dashboard_.dash-metrics_article]:[border:0]",
    "[&.admin-dark_.admin-dashboard_.dash-stock_li]:bg-[#242424]",
    "[&.admin-dark_.admin-dashboard_.dash-stock_li]:text-[#eee]",
    "[&.admin-dark_.admin-dashboard_.dash-stock_li]:[border:0]",
    "[&.admin-dark_.admin-dashboard_.dash-panel-2_.dash-catalog>div]:bg-[#242424]",
    "[&.admin-dark_.admin-dashboard_.dash-panel-2_.dash-catalog>div]:text-[#eee]",
    "[&.admin-dark_.admin-dashboard_.dash-panel-2_.dash-catalog>div]:[border:0]",
    "[&.admin-dark_.admin-dashboard_.dash-blue]:bg-[#18243b]",
    "[&.admin-dark_.admin-sidebar_nav_a[aria-current=page]]:bg-[#252525]",
    "[&.admin-dark_.admin-sidebar_nav_a[aria-current=page]]:[border:0]",
    "[&.admin-dark_.admin-sidebar_nav_a[aria-current=page]]:shadow-none",
    "[&.admin-dark_.admin-main_select]:[border:0] [&.admin-dark_.admin-main_select]:shadow-none",
    "[&.admin-dark_.admin-main_input:not([type=checkbox]):not([type=radio]):not([type=file])]:[border:0]",
    "[&.admin-dark_.admin-main_input:not([type=checkbox]):not([type=radio]):not([type=file])]:shadow-none",
    "[&.admin-dark_.admin-search-field]:[border:0]",
    "[&.admin-dark_.admin-search-field]:shadow-none",
    "[&.admin-dark_.admin-search-results]:[border:0]",
    "[&.admin-dark_.admin-search-results]:shadow-none",
    "[&.admin-dark_.admin-search-field:focus-within]:shadow-none",
    "[&.admin-dark_.admin-search-field:focus-within]:bg-[#2b2b2b]",
    "[&.admin-dark_.admin-search-field_input:focus]:outline-none",
    "[&.admin-dark_.admin-search-field_input:focus]:shadow-none",
    "[&.admin-dark_.admin-main_select:focus]:outline-none",
    "[&.admin-dark_.admin-main_select:focus]:shadow-none",
    "[&.admin-dark_.admin-main_input:focus]:outline-none",
    "[&.admin-dark_.admin-main_input:focus]:shadow-none",
    "[&.admin-dark_.admin-search-field_input:focus-visible]:[outline:1px_solid_#bcbcbc]",
    "[&.admin-dark_.admin-search-field_input:focus-visible]:[outline-offset:-4px]",
    "[&.admin-dark_.admin-search-field_input:focus-visible]:shadow-none",
    "[&.admin-dark_.admin-main_select:focus-visible]:[outline:1px_solid_#bcbcbc]",
    "[&.admin-dark_.admin-main_select:focus-visible]:[outline-offset:-4px]",
    "[&.admin-dark_.admin-main_select:focus-visible]:shadow-none",
    "[&.admin-dark_.admin-main_input:focus-visible]:[outline:1px_solid_#bcbcbc]",
    "[&.admin-dark_.admin-main_input:focus-visible]:[outline-offset:-4px]",
    "[&.admin-dark_.admin-main_input:focus-visible]:shadow-none",
    "[&.admin-dark_.admin-sidebar_nav_a:focus-visible]:[outline:1px_solid_#bcbcbc]",
    "[&.admin-dark_.admin-sidebar_nav_a:focus-visible]:[outline-offset:-4px]",
    "[&.admin-dark_.admin-sidebar_nav_a:focus-visible]:shadow-none",
  ].join(" "),
  customerMetrics: [
    "customer-metrics grid grid-cols-[repeat(3,minmax(0,1fr))] gap-[14px] mt-6 mr-0 mb-6 ml-0",
    "[&_article]:pt-5 [&_article]:pr-5 [&_article]:pb-5 [&_article]:pl-5",
    "[&_article]:bg-[#ededed] [&_article]:rounded-[20px] [&_article:nth-child(2)]:bg-[#f0f0f0]",
    "[&_article:nth-child(3)]:bg-[#eeeeee] [&_p]:text-[11px] [&_p]:text-[#666666]",
    "[&_strong]:block [&_strong]:text-[30px] [&_strong]:font-medium [&_strong]:mt-3",
    "[@media(max-width:600px)]:gap-2 [@media(max-width:600px)]:[&_article]:pt-[14px]",
    "[@media(max-width:600px)]:[&_article]:pr-[14px]",
    "[@media(max-width:600px)]:[&_article]:pb-[14px]",
    "[@media(max-width:600px)]:[&_article]:pl-[14px]",
    "[@media(max-width:600px)]:[&_strong]:text-[24px]",
  ].join(" "),
  customerFilter: [
    "customer-filter flex items-center gap-3 flex-wrap bg-[#f5f5f9] pt-[10px] pr-[10px]",
    "pb-[10px] pl-[10px] [@media(max-width:600px)]:[&>label:first-child]:[flex-basis:100%]",
  ].join(" "),
  customerAvatar: [
    "customer-avatar w-[38px] h-[38px] grid place-items-center rounded-[13px] bg-[#ebebeb]",
    "text-[#696969] shrink-0",
  ].join(" "),
  customerStatus: [
    "customer-status inline-block whitespace-nowrap pt-[6px] pr-[10px] pb-[6px] pl-[10px]",
    "rounded-[20px] text-[10px] bg-[#f0f0f0] text-[#6a6a6a] [&.confirmed]:bg-[#eeeeee]",
    "[&.confirmed]:text-[#646464]",
  ].join(" "),
  customerRole: ["customer-role text-[9px] text-[#6a6a6a]"].join(" "),
  customersPage: ["customers-page [&_table]:min-w-[690px]"].join(" "),
  adminBrand: [
    "admin-brand [&>span]:block [&>span]:font-medium [&_img]:block [&_img]:w-[110px]",
    "[&_img]:h-auto [&_img]:max-w-full [&>span]:text-[8px] [&>span]:tracking-[.26em]",
    "[&>span]:text-[#666] [&>span]:mt-0 [&>span]:mr-0 [&>span]:mb-2 [&>span]:ml-0",
    "[&>span]:pl-[.26em] [@media(max-width:800px)]:[&_img]:w-[95px]",
    "[@media(max-width:800px)]:[&>span]:text-[7px] [@media(max-width:800px)]:[&>span]:mb-[6px]",
  ].join(" "),
  adminAccountAvatar: [
    "admin-account-avatar w-9 h-9 grid place-items-center rounded-full text-[13px]",
    "[@media(max-width:800px)]:w-[30px] [@media(max-width:800px)]:h-[30px] bg-[#e7e7e7]",
    "text-[#1e1e1e]",
  ].join(" "),
  adminAccount: [
    "admin-account [&>div]:min-w-0 [&_strong]:block [&_strong]:text-[11px]",
    "[&_strong]:font-medium [&>div>span]:block [&>div>span]:text-[10px]",
    "[&>div>span]:text-[#7a7a7a] [&>div>span]:max-w-[190px] [&>div>span]:overflow-hidden",
    "[&>div>span]:text-ellipsis [@media(max-width:1100px)]:[&>div]:hidden",
  ].join(" "),
  adminSearch: [
    "admin-search relative min-w-0 z-[40] [@media(max-width:800px)]:[grid-column:1/-1]",
    "[@media(max-width:800px)]:[grid-row:2]",
  ].join(" "),
  adminSearchField: [
    "admin-search-field flex items-center gap-[10px] bg-white rounded-[30px] pt-0 pr-4 pb-0 pl-4",
    "min-h-11 text-[#8e8e8e] [&_input]:flex-1 [&_input]:min-w-0 [&_input]:[border:0]",
    "[&_input]:bg-transparent [&_input]:outline-none [&_input]:pt-[13px] [&_input]:pr-0",
    "[&_input]:pb-[13px] [&_input]:pl-0 [&_input]:text-[12px] [&_input]:text-[#313131]",
    "[&_kbd]:text-[10px] [&_kbd]:bg-[#f6f5f9] [&_kbd]:rounded-[6px] [&_kbd]:pt-1 [&_kbd]:pr-1",
    "[&_kbd]:pb-1 [&_kbd]:pl-1 [&_kbd]:whitespace-nowrap [&_button]:pt-[6px] [&_button]:pr-[6px]",
    "[&_button]:pb-[6px] [&_button]:pl-[6px] [@media(max-width:800px)]:[&_input]:text-[16px]",
    "[@media(max-width:800px)]:[&_kbd]:hidden [&:focus-within]:shadow-[0_0_0_2px_#2d416f]",
  ].join(" "),
  adminSearchResults: [
    "admin-search-results absolute top-[calc(100%_+_10px)] left-0 right-0 min-w-80",
    "max-h-[min(70dvh,580px)] overflow-auto bg-white [border:1px_solid_#ededed] rounded-[20px]",
    "shadow-[0_18px_60px_#34343420] pt-3 pr-3 pb-3 pl-3 [&_h2]:flex [&_h2]:justify-between",
    "[&_h2]:text-[11px] [&_h2]:font-semibold [&_h2]:text-[#5b5b5b] [&_h2]:pt-3 [&_h2]:pr-[10px]",
    "[&_h2]:pb-[6px] [&_h2]:pl-[10px] [&_h2>span]:font-normal [&_h2>span]:text-[#999]",
    "[&_h2>span]:text-[9px] [&_section>a]:flex [&_section>a]:justify-between",
    "[&_section>a]:items-center [&_section>a]:gap-3 [&_section>a]:pt-3 [&_section>a]:pr-[10px]",
    "[&_section>a]:pb-3 [&_section>a]:pl-[10px] [&_section>a]:rounded-[12px]",
    "[&_section>a]:bg-transparent [&_section>a]:mt-[2px] [&_section>a]:mr-0",
    "[&_section>a]:mb-[2px] [&_section>a]:ml-0 [&_section>a]:no-underline",
    "[&_section>a:hover]:bg-[#f2f2f2] [&_section>a:focus-visible]:bg-[#f2f2f2] [&_strong]:block",
    "[&_strong]:font-medium [&_strong]:text-[12px] [&_strong]:text-[#313131] [&_small]:block",
    "[&_small]:text-[10px] [&_small]:text-[#7d7d7d] [&_small]:mt-1 [&_small]:wrap-anywhere",
    "[&_section>a>span]:min-w-0 [&_svg]:shrink-0 [@media(max-width:800px)]:min-w-0",
    "[@media(max-width:800px)]:max-h-[65dvh]",
  ].join(" "),
  searchCaption: [
    "search-caption flex items-center justify-between text-[10px] text-[#838383] pt-[5px] pr-2",
    "pb-[10px] pl-2 [&_button]:pt-[6px] [&_button]:pr-[6px] [&_button]:pb-[6px]",
    "[&_button]:pl-[6px]",
  ].join(" "),
  searchMessage: [
    "search-message text-[12px] leading-[1.8] text-[#777] pt-[18px] pr-[10px] pb-[18px]",
    "pl-[10px]",
  ].join(" "),
} as const satisfies Record<string, string>;
