// Tailwind utilities grouped by component. Keep the marker class for descendant variants.
export const homeStyles = {
  beecahHome: [
    "beecah-home [&_.home-collection]:mr-3 [&_.home-collection]:mb-9 [&_.home-collection]:ml-3",
    "[&_.home-collection_h2]:text-[clamp(32px,4.2vw,54px)]",
    "[&_.home-collection_h2]:leading-[1.15] [&_.home-collection_h2]:max-w-175",
    "[&_.collection-filters]:[border:0] [&_.collection-filters]:mt-[26px]",
    "[&_.collection-filters]:mb-6 [&_.collection-filters>div]:gap-[7px]",
    "[&_.collection-filters>div]:pt-1 [&_.collection-filters>div]:pr-0",
    "[&_.collection-filters>div]:pb-1 [&_.collection-filters>div]:pl-0",
    "[&_.collection-filters_button]:[border:0] [&_.collection-filters_button]:min-h-11",
    "[&_.collection-filters_button]:pt-[10px] [&_.collection-filters_button]:pr-[18px]",
    "[&_.collection-filters_button]:pb-[10px] [&_.collection-filters_button]:pl-[18px]",
    "[&_.collection-filters_button]:text-[12px]",
    "[&_.collection-filters_button:hover]:shadow-[0_2px_10px_#2d416f10]",
    "[&_.collection-products]:gap-4 [&_.collection-products_article]:bg-white",
    "[&_.collection-products_article]:[transition:box-shadow_.2s,transform_.2s]",
    "[&_.collection-products_article:hover]:shadow-[0_10px_30px_#443e5610]",
    "[&_.collection-products_article:hover]:[transform:translateY(-3px)]",
    "[&_.collection-products_article>div:first-child]:bg-[#f5f3f1]",
    "[&_.collection-products_article>div:last-child]:pt-4",
    "[&_.collection-products_article>div:last-child]:pr-[9px]",
    "[&_.collection-products_article>div:last-child]:pb-[9px]",
    "[&_.collection-products_article>div:last-child]:pl-[9px]",
    "[&_.collection-products_article_h3]:text-[17px]",
    "[&_.collection-products_article>div:last-child>div:last-of-type]:[border-top:1px_solid_#f1eeeb]",
    "[&_.collection-products_article>div:last-child>div:last-of-type]:mt-[14px]",
    "[&_.collection-products_article>div:last-child>div:last-of-type]:pt-[14px]",
    "[&_section[aria-labelledby=notes-heading]]:mt-[30px]",
    "[&_section[aria-labelledby=notes-heading]]:rounded-[26px]",
    '[&_section[aria-labelledby=notes-heading]_h2]:[font-family:"Sorts_Mill_Goudy",serif]',
    "[&_section[aria-labelledby=notes-heading]_h2]:italic",
    "[&_section[aria-labelledby=notes-heading]_h2]:text-[42px]",
    "[&_section[aria-labelledby=notes-heading]_h2]:font-normal",
    "[&_section[aria-labelledby=notes-heading]_h2]:tracking-[-.03em]",
    "[&_section[aria-labelledby=notes-heading]_a]:px-[14px]",
    "[&_section[aria-labelledby=notes-heading]_a]:mb-2",
    "[&_section[aria-labelledby=notes-heading]_a]:[border:1px_solid_#ffffff1c]",
    "[&_section[aria-labelledby=notes-heading]_a]:rounded-[14px]",
    "[&_section[aria-labelledby=notes-heading]_a]:bg-[#ffffff07]",
    "[&_section[aria-labelledby=notes-heading]_a:hover]:bg-[#ffffff13]",
    "[&_section[aria-labelledby=notes-heading]_a>span:nth-child(2)]:text-[#ffffffa0]",
    "[&_section[aria-labelledby=notes-heading]_.border-t]:[border:0]",
    "[&_section[aria-labelledby=beecah-heading]]:items-center",
    "[&_section[aria-labelledby=faq-heading]]:[border:0]",
    "[&_section[aria-labelledby=faq-heading]]:pt-[26px]",
    "[&_section[aria-labelledby=faq-heading]_details]:[border:0]",
    "[&_section[aria-labelledby=faq-heading]_details]:bg-[#f6f6f4]",
    "[&_section[aria-labelledby=faq-heading]_details]:rounded-[16px]",
    "[&_section[aria-labelledby=faq-heading]_details]:mb-[10px]",
    "[&_section[aria-labelledby=faq-heading]_details]:pt-0",
    "[&_section[aria-labelledby=faq-heading]_details]:pr-5",
    "[&_section[aria-labelledby=faq-heading]_details]:pb-0",
    "[&_section[aria-labelledby=faq-heading]_details]:pl-5",
    "[&_section[aria-labelledby=faq-heading]_details[open]]:bg-[#eef0f5]",
    "[&_section[aria-labelledby=faq-heading]_summary]:min-h-16",
    "[&_section[aria-labelledby=faq-heading]_details_p]:text-[#626777]",
    "[@media(max-width:640px)]:[&_.home-collection]:mr-3",
    "[@media(max-width:640px)]:[&_.home-collection]:mb-6",
    "[@media(max-width:640px)]:[&_.home-collection]:ml-3",
    "[@media(max-width:640px)]:[&_.home-collection_h2]:text-[34px]",
    "[@media(max-width:640px)]:[&_.collection-filters_button]:pt-[10px]",
    "[@media(max-width:640px)]:[&_.collection-filters_button]:pr-[15px]",
    "[@media(max-width:640px)]:[&_.collection-filters_button]:pb-[10px]",
    "[@media(max-width:640px)]:[&_.collection-filters_button]:pl-[15px]",
    "[@media(max-width:640px)]:[&_.collection-filters_button]:text-[11px]",
    "[@media(max-width:640px)]:[&_.collection-products]:gap-[10px]",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child]:pt-3",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child]:pr-1",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child]:pb-[6px]",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child]:pl-1",
    "[@media(max-width:640px)]:[&_.collection-products_article_h3]:text-[14px]",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child>div:last-of-type]:gap-1",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child>div:last-of-type_button]:w-10",
    "[@media(max-width:640px)]:[&_.collection-products_article>div:last-child>div:last-of-type_button]:h-11",
    "[@media(max-width:640px)]:[&_.home-collection>div:last-child]:flex-wrap",
    "[@media(max-width:640px)]:[&_.home-collection>div:last-child]:gap-4",
    "[@media(max-width:640px)]:[&_.home-collection>div:last-child]:leading-[1.7]",
    "[@media(max-width:640px)]:[&_section[aria-labelledby=beecah-heading]]:gap-6",
    "[@media(max-width:640px)]:[&_section[aria-labelledby=notes-heading]_h2]:text-[35px]",
    "[@media(prefers-reduced-motion:reduce)]:[&_.collection-products_article:hover]:[transform:none]",
    "[&_.home-intro]:flex [&_.home-intro]:justify-between [&_.home-intro]:gap-5",
    "[&_.home-intro]:pt-[30px] [&_.home-intro]:pr-6 [&_.home-intro]:pb-[22px]",
    "[&_.home-intro]:pl-6 [&_.home-intro]:text-[12px] [&_.home-intro]:text-[#555]",
    "[&_.home-collection]:bg-[#f6f5f2] [&_.home-collection]:mt-10 [&_.home-collection]:pt-11",
    "[&_.home-collection]:pr-7 [&_.home-collection]:pb-11 [&_.home-collection]:pl-7",
    "[&_.home-collection]:rounded-[20px] [&_.collection-products_article]:shadow-none",
    "[&_.collection-products_article]:[border:0] [&_.collection-products_article]:rounded-[14px]",
    "[&_.collection-products_article]:pt-2 [&_.collection-products_article]:pr-2",
    "[&_.collection-products_article]:pb-2 [&_.collection-products_article]:pl-2",
    "[&_.collection-products_article>div:first-child]:rounded-[10px]",
    "[&_.collection-filters_button]:bg-transparent [&_.collection-filters_button]:rounded-[8px]",
    "[&_.collection-filters_button]:text-[#555]",
    "[&_.collection-filters_button[aria-pressed=true]]:bg-[#1e1e1e]",
    "[&_.collection-filters_button[aria-pressed=true]]:text-white",
    "[&_section[aria-labelledby=beecah-heading]]:bg-white",
    "[&_section[aria-labelledby=beecah-heading]]:mt-8",
    "[&_section[aria-labelledby=beecah-heading]]:mr-3",
    "[&_section[aria-labelledby=beecah-heading]]:mb-8",
    "[&_section[aria-labelledby=beecah-heading]]:ml-3",
    "[&_section[aria-labelledby=beecah-heading]]:pt-14",
    "[&_section[aria-labelledby=beecah-heading]]:pr-7",
    "[&_section[aria-labelledby=beecah-heading]]:pb-14",
    "[&_section[aria-labelledby=beecah-heading]]:pl-7",
    "[&_section[aria-labelledby=beecah-heading]]:rounded-none",
    "[&_section[aria-labelledby=beecah-heading]]:[border-top:1px_solid_#e7e5e1]",
    "[&_section[aria-labelledby=beecah-heading]]:[border-bottom:1px_solid_#e7e5e1]",
    "[&_.home-eyebrow]:text-[10px] [&_.home-eyebrow]:tracking-[.19em]",
    "[&_.home-eyebrow]:uppercase [&_.home-eyebrow]:leading-[1.7] [&_.home-coming]:grid",
    "[&_.home-coming]:grid-cols-[1fr_1fr] [&_.home-coming]:mt-10 [&_.home-coming]:mr-3",
    "[&_.home-coming]:mb-10 [&_.home-coming]:ml-3 [&_.home-coming]:rounded-[20px]",
    "[&_.home-coming]:overflow-hidden [&_.home-coming]:bg-[#eeede8] [&_.home-button]:inline-flex",
    "[&_.home-button]:items-center [&_.home-button]:justify-between [&_.home-button]:gap-7",
    "[&_.home-button]:min-h-[50px] [&_.home-button]:mt-3 [&_.home-button]:pt-[15px]",
    "[&_.home-button]:pr-[22px] [&_.home-button]:pb-[15px] [&_.home-button]:pl-[22px]",
    "[&_.home-button]:rounded-[12px] [&_.home-button]:bg-[#1e1e1e] [&_.home-button]:text-white",
    "[&_.home-button]:text-[12px] [&_.home-button]:[transition:background_.2s]",
    "[&_.home-button:hover]:bg-[#2d416f] [&_a:focus-visible]:[outline:2px_solid_#2d416f]",
    "[&_a:focus-visible]:[outline-offset:4px]",
    "[&_button:focus-visible]:[outline:2px_solid_#2d416f]",
    "[&_button:focus-visible]:[outline-offset:4px]",
    "[&_summary:focus-visible]:[outline:2px_solid_#2d416f]",
    "[&_summary:focus-visible]:[outline-offset:4px] [&_.home-contact]:grid",
    "[&_.home-contact]:grid-cols-[1.2fr_1fr] [&_.home-contact]:gap-15",
    "[&_.home-contact]:items-center [&_.home-contact]:pt-13 [&_.home-contact]:pr-10",
    "[&_.home-contact]:pb-13 [&_.home-contact]:pl-10 [&_.home-contact]:mt-8",
    "[&_.home-contact]:mr-3 [&_.home-contact]:mb-12 [&_.home-contact]:ml-3",
    "[&_.home-contact]:rounded-[20px] [&_.home-contact]:bg-[#e9edf3]",
    "[@media(max-width:760px)]:[&_.home-coming]:grid-cols-[1fr]",
    "[@media(max-width:760px)]:[&_.home-contact]:grid-cols-[1fr]",
    "[@media(max-width:760px)]:[&_.home-contact]:pt-[34px]",
    "[@media(max-width:760px)]:[&_.home-contact]:pr-[26px]",
    "[@media(max-width:760px)]:[&_.home-contact]:pb-[34px]",
    "[@media(max-width:760px)]:[&_.home-contact]:pl-[26px]",
    "[@media(max-width:760px)]:[&_.home-contact]:gap-6",
    "[@media(max-width:760px)]:[&_.home-intro]:pt-[22px]",
    "[@media(max-width:760px)]:[&_.home-intro]:pr-4",
    "[@media(max-width:760px)]:[&_.home-intro]:pb-[22px]",
    "[@media(max-width:760px)]:[&_.home-intro]:pl-4",
    "[@media(max-width:760px)]:[&_.home-intro]:flex-wrap",
    "[@media(max-width:760px)]:[&_.home-intro]:gap-[10px]",
    "[@media(max-width:760px)]:[&_.home-intro]:text-[11px]",
    "[@media(max-width:760px)]:[&_.home-collection]:pt-7",
    "[@media(max-width:760px)]:[&_.home-collection]:pr-3",
    "[@media(max-width:760px)]:[&_.home-collection]:pb-7",
    "[@media(max-width:760px)]:[&_.home-collection]:pl-3",
    "[@media(max-width:760px)]:[&_section[aria-labelledby=beecah-heading]]:pt-9",
    "[@media(max-width:760px)]:[&_section[aria-labelledby=beecah-heading]]:pr-5",
    "[@media(max-width:760px)]:[&_section[aria-labelledby=beecah-heading]]:pb-9",
    "[@media(max-width:760px)]:[&_section[aria-labelledby=beecah-heading]]:pl-5",
  ].join(" "),
  homeIntro: ["home-intro [&>a]:text-[#202c43]"].join(" "),
  homeComingCopy: [
    "home-coming-copy pt-[54px] pr-[42px] pb-[54px] pl-[42px] self-center",
    "[&>p:not(.home-eyebrow)]:max-w-[390px] [&>p:not(.home-eyebrow)]:text-[14px]",
    "[&>p:not(.home-eyebrow)]:leading-[1.9] [&>p:not(.home-eyebrow)]:text-[#5d5d58]",
    "[&>p:not(.home-eyebrow)]:mt-[18px] [&>p:not(.home-eyebrow)]:mr-0",
    "[&>p:not(.home-eyebrow)]:mb-[18px] [&>p:not(.home-eyebrow)]:ml-0",
    "[@media(max-width:760px)]:pt-[34px] [@media(max-width:760px)]:pr-[26px]",
    "[@media(max-width:760px)]:pb-[34px] [@media(max-width:760px)]:pl-[26px]",
  ].join(" "),
  homeComing: [
    'home-coming [&_h2]:[font-family:"Sorts_Mill_Goudy",serif]',
    "[&_h2]:text-[clamp(34px,4vw,54px)] [&_h2]:font-normal [&_h2]:tracking-[-.035em]",
    "[&_h2]:leading-[1.15] [&_h2]:mt-[22px] [&_h2]:mr-0 [&_h2]:mb-[22px] [&_h2]:ml-0",
    '[&_h1]:[font-family:"Sorts_Mill_Goudy",serif] [&_h1]:text-[clamp(34px,4vw,54px)]',
    "[&_h1]:font-normal [&_h1]:tracking-[-.035em] [&_h1]:leading-[1.15] [&_h1]:mt-[22px]",
    "[&_h1]:mr-0 [&_h1]:mb-[22px] [&_h1]:ml-0 [&_em]:text-[#2d416f]",
    "[@media(max-width:760px)]:[&_h2]:text-[38px] [@media(max-width:760px)]:[&_h1]:text-[38px]",
  ].join(" "),
  homeContact: [
    'home-contact [&_h2]:[font-family:"Sorts_Mill_Goudy",serif]',
    "[&_h2]:text-[clamp(34px,4vw,54px)] [&_h2]:font-normal [&_h2]:tracking-[-.035em]",
    "[&_h2]:leading-[1.15] [&_h2]:mt-[22px] [&_h2]:mr-0 [&_h2]:ml-0 [&_h2]:mb-0",
    "[&>div>p:not(.home-eyebrow)]:max-w-[370px] [&>div>p:not(.home-eyebrow)]:text-[#566073]",
    "[&>div>p:not(.home-eyebrow)]:text-[14px] [&>div>p:not(.home-eyebrow)]:leading-[1.9]",
    "[@media(max-width:760px)]:[&_h2]:text-[38px]",
  ].join(" "),
  homeComingImage: [
    "home-coming-image relative min-h-110 [&>span]:absolute [&>span]:bottom-6 [&>span]:left-6",
    "[&>span]:z-[1] [&>span]:rounded-[30px] [&>span]:bg-[#ffffffed] [&>span]:pt-[10px]",
    "[&>span]:pr-[18px] [&>span]:pb-[10px] [&>span]:pl-[18px] [&>span]:text-[10px]",
    "[&>span]:tracking-[.12em] [&>span]:uppercase [@media(max-width:760px)]:min-h-75",
    "[@media(max-width:760px)]:max-h-90",
  ].join(" "),
  homeContactSecondary: [
    "home-contact-secondary block w-[fit-content] mt-5 text-[11px] underline",
    "[text-underline-offset:5px] text-[#39465c]",
  ].join(" "),
  newsBreadcrumb: [
    "news-breadcrumb flex gap-3 pt-[30px] pr-6 pb-0 pl-6 text-[12px] text-[#666]",
  ].join(" "),
} as const satisfies Record<string, string>;
