import type { ContentDictionary } from "./types";

/** Textos da interface: account. */
export const accountContent = {
  prefersReducedMotionReduce: "(prefers-reduced-motion: reduce)",
  informeSeuNome: "Informe seu nome.",
  informeSeuEMail: "Informe seu e-mail.",
  aSenhaPrecisaTerPeloMenos6Caracteres: "A senha precisa ter pelo menos 6 caracteres.",
  asSenhasNaoCoincidem: "As senhas não coincidem.",
  naoFoiPossivelCriarSuaConta: "Não foi possível criar sua conta.",
  contaCriadaVerifiqueSeuEMailParaConfirmar:
    "Conta criada. Verifique seu e-mail para confirmar o cadastro.",
  ocorreuUmErroAoCriarSuaConta: "Ocorreu um erro ao criar sua conta.",
  videoDeUmFrascoDePerfumeSobrePedras: "Vídeo de um frasco de perfume sobre pedras",
  pausarVideo: "Pausar vídeo",
  reproduzirVideo: "Reproduzir vídeo",
  beecahCollection: "Beecah Collection",
  encontreOSeu: "Encontre o seu",
  proximoPerfume: "próximo perfume.",
  salveSuasEscolhasEAcompanheCadaNovaDescoberta:
    "Salve suas escolhas e acompanhe cada nova descoberta.",
  soMaisUmPasso: "Só mais um passo",
  confiraSeuEMail: "Confira seu e-mail.",
  enviamosAsInstrucoesDeConfirmacaoPara: "Enviamos as instruções de confirmação para",
  abraAMensagemParaConcluirSeuCadastro: ". Abra a mensagem para concluir seu cadastro.",
  naoEncontrouVerifiqueTambemAPastaDeSpam:
    "Não encontrou? Verifique também a pasta de spam.",
  irParaOLogin: "Ir para o login ",
  precisoDeAjuda: "Preciso de ajuda",
  seuEspacoBeecah: "Seu espaço Beecah",
  crieSua: "Crie sua",
  conta: "conta.",
  guardeSeusFavoritosEAcompanheSeusPedidos:
    "Guarde seus favoritos e acompanhe seus pedidos.",
  nomeCompleto: "Nome completo",
  comoPodemosChamarVoce: "Como podemos chamar você?",
  eMail: "E-mail",
  voceEmailCom: "voce@email.com",
  senha: "Senha",
  ocultarSenhas: "Ocultar senhas",
  mostrarSenhas: "Mostrar senhas",
  crieUmaSenha: "Crie uma senha",
  usePeloMenos6Caracteres: "Use pelo menos 6 caracteres.",
  confirmarSenha: "Confirmar senha",
  repitaSuaSenha: "Repita sua senha",
  asSenhasPrecisamSerIguais: "As senhas precisam ser iguais.",
  criandoSuaConta: "Criando sua conta…",
  criarMinhaConta: "Criar minha conta",
  jaTemUmaConta: "Já tem uma conta?",
  entrar: "Entrar",
  informeSuaSenha: "Informe sua senha.",
  eMailOuSenhaInvalidos: "E-mail ou senha inválidos.",
  naoFoiPossivelEntrarNaConta: "Não foi possível entrar na conta.",
  ocorreuUmErroAoEntrarNaConta: "Ocorreu um erro ao entrar na conta.",
  umMomentoBeecahEntreFloresEFragrancias: "Um momento Beecah, entre flores e fragrâncias",
  seuProximo: "Seu próximo",
  encontro: "encontro.",
  fragranciasEscolhidasParaFazerParteDosSeusMomentos:
    "Fragrâncias escolhidas para fazer parte dos seus momentos.",
  queBomTer: "Que bom ter",
  voceDeVolta: "você de volta.",
  entreParaAcompanharSeusPedidosSalvarFavoritosE:
    "Entre para acompanhar seus pedidos, salvar favoritos e continuar suas descobertas.",
  suaSenha: "Sua senha",
  ocultarSenha: "Ocultar senha",
  mostrarSenha: "Mostrar senha",
  entrando: "Entrando…",
  entrarNaMinhaConta: "Entrar na minha conta",
  suaProximaDescobertaComecaAqui: "Sua próxima descoberta começa aqui",
  primeiraVezNaBeecah: "Primeira vez na Beecah? ",
  criarConta: "Criar conta",
  acessoASuaConta: " Acesso à sua conta",
  precisaDeAjuda: "Precisa de ajuda?",
  fullNamePhoneCpf: "\n          full_name,\n          phone,\n          cpf\n        ",
  erroAoCarregarPerfil: "Erro ao carregar perfil:",
  naoFoiPossivelCarregarSeusDados: "Não foi possível carregar seus dados.",
  naoFoiPossivelCarregarOsDadosAtualizeA:
    "Não foi possível carregar os dados. Atualize a página para tentar novamente.",
  informeSeuTelefone: "Informe seu telefone.",
  informeSeuCpf: "Informe seu CPF.",
  informeUmCpfValido: "Informe um CPF válido.",
  erroAoAtualizarPerfil: "Erro ao atualizar perfil:",
  naoFoiPossivelSalvarSeusDados: "Não foi possível salvar seus dados.",
  dadosAtualizadosComSucesso: "Dados atualizados com sucesso.",
  naoFoiPossivelSalvarVerifiqueSuaConexaoE:
    "Não foi possível salvar. Verifique sua conexão e tente novamente.",
  carregandoSuasInformacoes: "Carregando suas informações…",
  minhaConta: "← Minha conta",
  minhaConta2: "Minha conta",
  dadosPessoais: "Dados pessoais",
  essasInformacoesSeraoUsadasNosSeusPedidosE:
    "Essas informações serão usadas nos seus pedidos e entregas.",
  cpf: "CPF",
  oCpfSeraUtilizadoNosDadosDoPedido:
    "O CPF será utilizado nos dados do pedido e da entrega.",
  telefone: "Telefone",
  informeUmNumeroComDdd: "Informe um número com DDD.",
  salvarDados: "Salvar dados",
  cancelar: "Cancelar",
  fullNamePhone: "\n          full_name,\n          phone\n        ",
  informeONomeDoDestinatario: "Informe o nome do destinatário.",
  informeOTelefone: "Informe o telefone.",
  informeUmCepValidoCom8Numeros: "Informe um CEP válido com 8 números.",
  informeARua: "Informe a rua.",
  informeONumero: "Informe o número.",
  informeOBairro: "Informe o bairro.",
  informeACidade: "Informe a cidade.",
  informeAUfCom2Letras: "Informe a UF com 2 letras.",
  erroAoRemoverEnderecoPrincipalAnterior: "Erro ao remover endereço principal anterior:",
  naoFoiPossivelAtualizarOEnderecoPrincipal:
    "Não foi possível atualizar o endereço principal.",
  erroAoCadastrarEndereco: "Erro ao cadastrar endereço:",
  naoFoiPossivelCadastrarOEndereco: "Não foi possível cadastrar o endereço.",
  entrega: "Entrega",
  adicionarEndereco: "Adicionar endereço",
  cadastreUmEnderecoParaReceberSeusPedidos:
    "Cadastre um endereço para receber seus pedidos.",
  nomeDoDestinatario: "Nome do destinatário",
  cep: "CEP",
  ruaAvenida: "Rua / Avenida",
  numero: "Número",
  complemento: "Complemento",
  apartamentoBloco: "Apartamento, bloco...",
  bairro: "Bairro",
  cidade: "Cidade",
  uf: "UF",
  sp: "SP",
  nomeDoEndereco: "Nome do endereço",
  casaTrabalho: "Casa, Trabalho...",
  usarComoEnderecoPrincipal: "Usar como endereço principal",
  salvarEndereco: "Salvar endereço",
  erroAoCarregarEndereco: "Erro ao carregar endereço:",
  naoFoiPossivelCarregarOEndereco: "Não foi possível carregar o endereço.",
  erroAoAtualizarEnderecoPrincipal: "Erro ao atualizar endereço principal:",
  naoFoiPossivelAlterarOEnderecoPrincipal:
    "Não foi possível alterar o endereço principal.",
  erroAoAtualizarEndereco: "Erro ao atualizar endereço:",
  naoFoiPossivelSalvarOEndereco: "Não foi possível salvar o endereço.",
  editarEndereco: "Editar endereço",
  atualizeOsDadosDoEnderecoDeEntrega: "Atualize os dados do endereço de entrega.",
  salvarAlteracoes: "Salvar alterações",
  fullNamePhone2: "\n        full_name,\n        phone\n      ",
  erroAoCarregarEnderecos: "Erro ao carregar endereços:",
  erroAoCarregarPedidos: "Erro ao carregar pedidos:",
  seuEspacoNaBeecah: "Seu espaço na Beecah",
  ola: "Olá",
  tudoSobreSeusPedidosEmUmSoLugar: "Tudo sobre seus pedidos, em um só lugar.",
  historicoDeCompras: "Histórico de compras",
  meusPedidos: "Meus pedidos",
  naoFoiPossivelCarregarSeusPedidosAtualizeA:
    "Não foi possível carregar seus pedidos. Atualize a página para tentar novamente.",
  aindaNaoHaPedidosPorAqui: "Ainda não há pedidos por aqui.",
  encontreSeuProximoPerfumeDepoisDaCompraAcompanhe:
    "Encontre seu próximo perfume. Depois da compra, acompanhe os detalhes por aqui.",
  explorarPerfumes: "Explorar perfumes ",
  pedido: "Pedido #",
  pagamento: "Pagamento: ",
  verDetalhes: "Ver detalhes ↗",
  informacoesPessoais: "Informações pessoais",
  dadosDaConta: "Dados da conta",
  editarDados: "Editar dados ↗",
  naoFoiPossivelCarregarSeusDadosAtualizeA:
    "Não foi possível carregar seus dados. Atualize a página para tentar novamente.",
  naoInformado: "Não informado",
  paraReceberSeusPerfumes: "Para receber seus perfumes",
  enderecos: "Endereços",
  adicionarEndereco2: "+ Adicionar endereço",
  naoFoiPossivelCarregarSeusEnderecosAtualizeA:
    "Não foi possível carregar seus endereços. Atualize a página para tentar novamente.",
  ondeVamosEntregar: "Onde vamos entregar?",
  salveSeuEnderecoEAgilizeSuaProximaCompra:
    "Salve seu endereço e agilize sua próxima compra.",
  cadastrarMeuEndereco: "Cadastrar meu endereço ↗",
  endereco: "Endereço",
  principal: "Principal",
  cep2: "CEP ",
  editarEndereco2: "Editar endereço ",
  editarEndereco3: "Editar endereço ↗",
  precisaDeAjudaComUmPedido: "Precisa de ajuda com um pedido?",
  faleComABeecah: "Fale com a Beecah ↗",
  detalhesDoPedido: "Detalhes do pedido",
  realizadoEm: "Realizado em ",
  status: "Status",
  total: "Total",
  idDoPagamento: "ID do pagamento",
  itensDoPedido: "Itens do pedido",
  symbol7: " × ",
  fecharPainelDaConta: "Fechar painel da conta",
  naoFoiPossivelVerificarSuaContaFecheO:
    "Não foi possível verificar sua conta. Feche o painel e tente novamente.",
  fullNamePhone3: "full_name, phone",
  seusDadosDePerfilNaoEstaoDisponiveisAgora:
    "Seus dados de perfil não estão disponíveis agora. Você ainda pode acessar sua conta.",
  naoFoiPossivelCarregarSuaContaTenteNovamente:
    "Não foi possível carregar sua conta. Tente novamente em instantes.",
  naoFoiPossivelSairDaContaTenteNovamente:
    "Não foi possível sair da conta. Tente novamente.",
  carregandoSuaConta: " Carregando sua conta…",
  meusDados: "Meus dados",
  informacoesPessoaisECadastro: "Informações pessoais e cadastro",
  acompanheSuasCompras: "Acompanhe suas compras",
  meusFavoritos: "Meus favoritos",
  suasProximasFragrancias: "Suas próximas fragrâncias",
  queBomTerVocePorAqui: "Que bom ter você por aqui.",
  ola2: "Olá, ",
  bemVindoABeecah: "Bem-vindo à Beecah.",
  nome: "Nome",
  completeSeuCadastro: "Complete seu cadastro",
  eMail2: " E-mail",
  telefone2: " Telefone",
  opcoesDaConta: "Opções da conta",
  saindo: "Saindo…",
  sairDaConta: "Sair da conta",
  fragranciasEMomentosBeecah: "Fragrâncias e momentos Beecah",
  umEspacoSoSeu: "Um espaço só seu",
  suasEscolhas: "Suas escolhas. ",
  seuPerfume: "Seu perfume.",
  entreParaAcompanharSeusPedidosGuardarFavoritosE:
    "Entre para acompanhar seus pedidos, guardar favoritos e encontrar suas próximas fragrâncias.",
  entrarNaMinhaConta2: "Entrar na minha conta ",
  criarUmaConta: "Criar uma conta",
  precisaDeAjudaFaleComABeecah: "Precisa de ajuda? Fale com a Beecah.",
  naoFoiPossivelSairTenteNovamente: "Não foi possível sair. Tente novamente.",
  visaoGeral: "Visão geral",
  continuarComprando: "Continuar comprando ",
  minhaBeecah: "Minha Beecah",
  navegacaoDaConta: "Navegação da conta",
  favoritos: "Favoritos",
  ocultar: "Ocultar",
  mostrar: "Mostrar",
  salvando: "Salvando...",
  casa: "Casa",
  aprovado: "Aprovado",
  pendente: "Pendente",
  recusado: "Recusado",
  cancelado: "Cancelado",
  reembolsado: "Reembolsado",
  expirado: "Expirado",
} as const satisfies ContentDictionary;
