import type { ContentDictionary } from "./types";

/** Textos da interface: admin. */
export const adminContent = {
  naoFoiPossivelCarregarOsBannersAtualizeA:
    "Não foi possível carregar os banners. Atualize a página.",
  nomeNaoInformado: "Nome não informado",
  eMailNaoInformado: "E-mail não informado",
  relacionamento: "Relacionamento",
  clientesEContas: "Clientes e contas",
  consulteCadastrosEEncontreOsPedidosDeCada:
    "Consulte cadastros e encontre os pedidos de cada pessoa.",
  clientesCadastrados: "Clientes cadastrados",
  eMailsConfirmadosClientes: "E-mails confirmados · clientes",
  administradores: "Administradores",
  buscarPorNomeOuEMail: "Buscar por nome ou e-mail",
  tipoDeConta: "Tipo de conta",
  clientes: "Clientes",
  todasAsContas: "Todas as contas",
  buscar: "Buscar",
  limpar: "Limpar",
  naoFoiPossivelCarregarOsCadastrosAtualizeA:
    "Não foi possível carregar os cadastros. Atualize a página para tentar novamente.",
  contasEncontradas: " contas encontradas",
  pagina: "Página ",
  de: " de ",
  cliente: "Cliente",
  cadastro: "Cadastro",
  eMail: "E-mail",
  pedidos: "Pedidos",
  acoes: "Ações",
  administrador: "Administrador",
  naoConfirmado: "Não confirmado",
  verPedidosDe: "Ver pedidos de ",
  verPedidos: "Ver pedidos ↗",
  nenhumCadastroEncontradoAjusteABuscaOuO:
    "Nenhum cadastro encontrado. Ajuste a busca ou o tipo de conta.",
  paginacaoDosClientes: "Paginação dos clientes",
  anterior: "← Anterior",
  proxima: "Próxima →",
  esgotado: "Esgotado",
  estoqueBaixo: "Estoque baixo",
  emEstoque: "Em estoque",
  erroAoCarregarEstoque: "Erro ao carregar estoque:",
  gestao: "Gestão",
  estoque: "Estoque",
  acompanheADisponibilidadeDosProdutosDaBeecah:
    "Acompanhe a disponibilidade dos produtos da Beecah.",
  produtos: "Produtos",
  unidadesEmEstoque: "Unidades em estoque",
  esgotados: "Esgotados",
  produto: "Produto",
  marca: "Marca",
  quantidade: "Quantidade",
  status: "Status",
  acao: "Ação",
  editarEstoque: "Editar estoque",
  nenhumProdutoCadastrado: "Nenhum produto cadastrado.",
  beecahCollection: "Beecah Collection",
  admin: "ADMIN",
  b: "B",
  verLoja: "Ver loja ↗",
  erroAoCarregarPedidosDoAdmin: "Erro ao carregar pedidos do admin:",
  erroAoCarregarUsuarioDoPedido: "Erro ao carregar usuário do pedido:",
  eMailNaoDisponivel: "E-mail não disponível",
  painel: "← Painel",
  acompanheOsPedidosRealizadosNaBeecah: "Acompanhe os pedidos realizados na Beecah.",
  pedidosDoClienteSelecionado: "Pedidos do cliente selecionado · ",
  voltarAosClientes: "Voltar aos clientes",
  verTodosOsPedidos: "Ver todos os pedidos",
  pedidoEMailOuPagamento: "Pedido, e-mail ou pagamento",
  todos: "Todos",
  pendentes: "Pendentes",
  aprovados: "Aprovados",
  recusados: "Recusados",
  cancelados: "Cancelados",
  reembolsados: "Reembolsados",
  expirados: "Expirados",
  filtrar: "Filtrar",
  pedidoEncontrado: "pedido encontrado",
  pedidosEncontrados: "pedidos encontrados",
  nenhumPedidoEncontrado: "Nenhum pedido encontrado.",
  clienteNaoIdentificado: "Cliente não identificado",
  pedido: "Pedido #",
  total: "Total",
  pagamento: "Pagamento",
  verDetalhes: "Ver detalhes",
  itens: "Itens",
  symbol2: " ×",
  erroAoCarregarClienteDoPedido: "Erro ao carregar cliente do pedido:",
  erroAoCarregarEnderecoDeEntregaDoPedido:
    "Erro ao carregar endereço de entrega do pedido:",
  pedidos2: "← Pedidos",
  detalhesDoPedido: "Detalhes do pedido",
  realizadoEm: "Realizado em ",
  ultimaAtualizacao: "Última atualização",
  enderecoDeEntrega: "Endereço de entrega",
  cep: "CEP:",
  estePedidoNaoPossuiUmEnderecoDeEntrega:
    "Este pedido não possui um endereço de entrega registrado.",
  entrega: "Entrega",
  transportadora: "Transportadora",
  naoInformada: "Não informada",
  servico: "Serviço",
  naoInformado: "Não informado",
  valorDoFrete: "Valor do frete",
  prazoEstimado: "Prazo estimado",
  informacoesDeFreteNaoDisponiveisParaEstePedido:
    "Informações de frete não disponíveis para este pedido.",
  itensDoPedido: "Itens do pedido",
  subtotal: "Subtotal",
  frete: "Frete",
  mercadoPago: "Mercado Pago",
  preferenceId: "Preference ID",
  naoDisponivel: "Não disponível",
  paymentId: "Payment ID",
  erroAoEnviarImagem: "Erro ao enviar imagem.",
  naoFoiPossivelCadastrar: "Não foi possível cadastrar.",
  produtoCriadoMasOIdNaoFoiRetornado: "Produto criado, mas o ID não foi retornado.",
  naoFoiPossivelCadastrarOProduto: "Não foi possível cadastrar o produto.",
  produtos2: "← Produtos",
  novoProduto: "Novo produto",
  cadastreUmNovoPerfumeNaBeecah: "Cadastre um novo perfume na Beecah.",
  informacoesBasicas: "Informações básicas",
  nomeDoPerfume: "Nome do perfume",
  exKhamrahQahwa: "Ex: Khamrah Qahwa",
  exLattafa: "Ex: Lattafa",
  generoDoPerfume: "Gênero do perfume",
  selecione: "Selecione",
  feminino: "Feminino",
  masculino: "Masculino",
  unissex: "Unissex",
  oGeneroEAsSelecoesAbaixoSaoIndependentes:
    "O gênero e as seleções abaixo são independentes.",
  perfumeArabe: " Perfume árabe",
  exibirEmNovos: " Exibir em Novos",
  umPerfumeFemininoEArabeApareceNasDuas:
    "Um perfume feminino e árabe aparece nas duas páginas e continua no catálogo geral. Mais vendidos é atualizado automaticamente pelas vendas aprovadas.",
  volume: "Volume",
  ex100ml: "Ex: 100ml",
  familiaOlfativa: "Família olfativa",
  exGourmand: "Ex: Gourmand",
  descricao: "Descrição",
  descricaoDoPerfume: "Descrição do perfume...",
  precoEEstoque: "Preço e estoque",
  preco: "Preço",
  precoPromocional: "Preço promocional",
  pesoEDimensoesParaEnvio: "Peso e dimensões para envio",
  informeOPesoEAsDimensoesDoProduto:
    "Informe o peso e as dimensões do produto já considerando a embalagem usada para envio.",
  pesoKg: "Peso (kg)",
  larguraCm: "Largura (cm)",
  alturaCm: "Altura (cm)",
  comprimentoCm: "Comprimento (cm)",
  essesDadosSeraoUtilizadosParaCalcularOFrete:
    "Esses dados serão utilizados para calcular o frete no checkout. Se preencher um deles, preencha os quatro.",
  piramideOlfativa: "Pirâmide olfativa",
  separeCadaNotaPorVirgula: "Separe cada nota por vírgula.",
  notasDeSaida: "Notas de saída",
  bergamotaLimaoLavanda: "Bergamota, Limão, Lavanda",
  notasDeCoracao: "Notas de coração",
  canelaPraline: "Canela, Pralinê",
  notasDeFundo: "Notas de fundo",
  baunilhaAmbarAlmiscar: "Baunilha, Âmbar, Almíscar",
  imagens: "Imagens",
  aPrimeiraImagemSeraUsadaComoCapa: "A primeira imagem será usada como capa.",
  selecionarImagens: "Selecionar imagens",
  jpgPngOuWebp: "JPG, PNG ou WEBP",
  imagemPrincipal: "Imagem principal",
  mb: " MB",
  publicacao: "Publicação",
  produtoAtivoNaLoja: "Produto ativo na loja",
  produtoEmDestaque: "Produto em destaque",
  cancelar: "Cancelar",
  cadastrarProduto: "Cadastrar produto",
  erroAoCarregarProdutos: "Erro ao carregar produtos:",
  gerencieOsPerfumesCadastradosNaBeecah: "Gerencie os perfumes cadastrados na Beecah.",
  novoProduto2: "+ Novo produto",
  categoria: "Categoria",
  ativo: "Ativo",
  inativo: "Inativo",
  ver: "Ver",
  editar: "Editar",
  naoFoiPossivelAtualizarOProduto: "Não foi possível atualizar o produto.",
  produtoAtualizadoComSucesso: "Produto atualizado com sucesso!",
  naoFoiPossivelAlterarACapa: "Não foi possível alterar a capa.",
  imagemPrincipalAlteradaComSucesso: "Imagem principal alterada com sucesso!",
  temCertezaQueDesejaExcluirEstaImagem: "Tem certeza que deseja excluir esta imagem?",
  naoFoiPossivelExcluirAImagem: "Não foi possível excluir a imagem.",
  imagemExcluidaComSucesso: "Imagem excluída com sucesso!",
  selecionePeloMenosUmaImagem: "Selecione pelo menos uma imagem.",
  imagemAdicionadaComSucesso: "Imagem adicionada com sucesso!",
  imagensAdicionadasComSucesso: "Imagens adicionadas com sucesso!",
  naoFoiPossivelEnviarAsImagens: "Não foi possível enviar as imagens.",
  estaAcaoNaoPoderaSerDesfeitaDesejaRealmente:
    "Esta ação não poderá ser desfeita. Deseja realmente continuar?",
  naoFoiPossivelExcluirOProduto: "Não foi possível excluir o produto.",
  editarProduto: "Editar produto",
  imagensDoProduto: "Imagens do produto",
  imagemCadastrada: "imagem cadastrada",
  imagensCadastradas: "imagens cadastradas",
  adicionarNovasImagens: "+ Adicionar novas imagens",
  imagemSelecionada: "imagem selecionada",
  imagensSelecionadas: "imagens selecionadas",
  mb2: "MB",
  remover: "Remover",
  enviandoImagens: "Enviando imagens...",
  enviarImagem: "Enviar imagem",
  nenhumaImagemCadastradaParaEsteProduto: "Nenhuma imagem cadastrada para este produto.",
  capa: "Capa",
  posicao: "Posição",
  definirComoCapa: "Definir como capa",
  excluirImagem: "Excluir imagem",
  zonaDePerigo: "Zona de perigo",
  aExclusaoRemovePermanentementeOProdutoDaLoja:
    "A exclusão remove permanentemente o produto da loja e também suas imagens.",
  excluindoProduto: "Excluindo produto...",
  excluirProduto: "Excluir produto",
  salvarAlteracoes: "Salvar alterações",
  eMailOuSenhaInvalidos: "E-mail ou senha inválidos.",
  naoFoiPossivelFazerLogin: "Não foi possível fazer login.",
  beecah: "Beecah",
  administracao: "Administração",
  entreComSuaContaDeAdministrador: "Entre com sua conta de administrador.",
  senha: "Senha",
  naoFoiPossivelConsultar: "Não foi possível consultar: ",
  naoFoiPossivelBuscarTenteNovamente: "Não foi possível buscar. Tente novamente.",
  buscarProdutosPedidosClientesESecoes: "Buscar produtos, pedidos, clientes e seções",
  buscarPerfumesPedidosClientes: "Buscar perfumes, pedidos, clientes…",
  limparBusca: "Limpar busca",
  ctrlK: "Ctrl K",
  resultadosDaBusca: "Resultados da busca",
  buscaEmTodaAAdministracao: "Busca em toda a administração ",
  fecharBusca: "Fechar busca",
  digitePeloMenos2CaracteresBusquePeloNome:
    "Digite pelo menos 2 caracteres. Busque pelo nome do perfume, marca, número do pedido, pagamento, nome ou e-mail do cliente.",
  buscando: "Buscando…",
  nenhumResultadoPara: "Nenhum resultado para “",
  tenteOutroTermo: "”. Tente outro termo.",
  ate6Resultados: "Até 6 resultados",
  useJpgPngOuWebpDeAte10: "Use JPG, PNG ou WebP de até 10 MB.",
  fotoEnviadaCliqueEmSalvarAlteracoesParaPublicar:
    "Foto enviada. Clique em Salvar alterações para publicar no banner.",
  naoFoiPossivelEnviarAFoto: "Não foi possível enviar a foto.",
  bannersSalvosAbraUmaNovaSessaoDoNavegador:
    "Banners salvos. Abra uma nova sessão do navegador para conferir o popup.",
  naoFoiPossivelSalvar: "Não foi possível salvar.",
  bannersPromocionais: "Banners promocionais",
  popupDeEntradaNaLojaApareceUmaVez:
    "Popup de entrada na loja. Aparece uma vez por sessão, na home ou no catálogo. Somente produtos ativos, em estoque e com preço promocional válido são exibidos.",
  ativarPopup: " Ativar popup",
  exibicao: "Exibição ",
  bannerFixo: "Banner fixo",
  slidesAutomaticos: "Slides automáticos",
  noModoFixoApareceOBannerFixadoOu:
    "No modo fixo, aparece o banner fixado ou o primeiro elegível da lista. Nos slides, o fixado abre primeiro e os demais seguem a ordem abaixo, a cada 6,5 segundos.",
  banner: "Banner ",
  moverBannerParaCima: "Mover banner para cima",
  moverBannerParaBaixo: "Mover banner para baixo",
  ativo2: " Ativo",
  fixado: " Fixado",
  removerEsteBannerARemocaoSeraAplicadaAo:
    "Remover este banner? A remoção será aplicada ao salvar.",
  titulo: "Título",
  fotoDesteBanner: "Foto deste banner",
  envieUmaImagemPropriaJpgPngOuWebp:
    "Envie uma imagem própria. JPG, PNG ou WebP, até 10 MB. Prefira uma foto vertical; ela será recortada para preencher o popup.",
  previaDaFotoDoBanner: "Prévia da foto do banner ",
  soltarImagemDoBanner: "Soltar imagem do banner ",
  solteApenasUmaImagemPorBanner: "Solte apenas uma imagem por banner.",
  enviandoFoto: "Enviando foto…",
  solteAImagemAqui: "Solte a imagem aqui",
  arrasteESolteAFotoAqui: "Arraste e solte a foto aqui",
  jpgPngOuWebpAte10Mb: "JPG, PNG ou WebP · até 10 MB",
  ouSelecioneOArquivoNoBotaoAbaixo: "Ou selecione o arquivo no botão abaixo.",
  trocarFoto: "Trocar foto",
  selecionarFoto: "Selecionar foto",
  removerFotoPersonalizadaEUsarADoProduto:
    "Remover foto personalizada e usar a do produto",
  semFotoPersonalizadaSeraUsadaAImagemDo:
    "Sem foto personalizada: será usada a imagem do produto.",
  imagemPersonalizadaUrlHttpsOuCaminhoLocal:
    "Imagem personalizada (URL HTTPS ou caminho local)",
  emBrancoUsarAFotoDoProduto: "Em branco: usar a foto do produto",
  esteProdutoNaoTemUmaPromocaoElegivelNo:
    "Este produto não tem uma promoção elegível no momento. O banner não aparecerá na loja.",
  umaOfertaParaVoce: "Uma oferta para você.",
  conhecaEstaFragranciaDaSelecaoBeecah: "Conheça esta fragrância da seleção Beecah.",
  adicionarBanner: "+ Adicionar banner",
  salvando: "Salvando…",
  operacao: "Operação",
  valorDosPedidosAprovados: "Valor dos pedidos aprovados",
  incluiFreteRegistradoNoPedido: "Inclui frete registrado no pedido",
  pedidosAprovados: "Pedidos aprovados",
  pedidosNoPeriodo: " pedidos no período",
  ticketMedio: "Ticket médio",
  valorAprovadoPedidosAprovados: "Valor aprovado ÷ pedidos aprovados",
  unidadesVendidas: "Unidades vendidas",
  somentePagamentosAprovados: "Somente pagamentos aprovados",
  nenhumPerfumeEncontradoTenteOutroNome: "Nenhum perfume encontrado. Tente outro nome.",
  aindaNaoHaDadosParaEsteRanking: "Ainda não há dados para este ranking.",
  beecahInteligenciaDaLoja: "Beecah · inteligência da loja",
  dashboard: "Dashboard",
  periodoDasVendas: "Período das vendas",
  ultimos7Dias: "Últimos 7 dias",
  ultimos30Dias: "Últimos 30 dias",
  ultimos90Dias: "Últimos 90 dias",
  atualizarIndicadores: "Atualizar indicadores",
  produto2: "+ Produto",
  secoesDoDashboard: "Seções do dashboard",
  atualizado: "Atualizado ",
  algunsDadosNaoCarregaramAtualizeParaTentarNovamente:
    "Alguns dados não carregaram. Atualize para tentar novamente. Fontes: ",
  evolucaoDasVendas: "Evolução das vendas",
  pedidosAprovadosPorDataDeCriacao: "Pedidos aprovados por data de criação · ",
  dias: " dias",
  vendasIndisponiveis: "Vendas indisponíveis.",
  valoresAprovadosPorIntervalo: "Valores aprovados por intervalo",
  cadaBarraAgrupaAproximadamente: "Cada barra agrupa aproximadamente ",
  diasValoresAtuaisSemPrevisao: " dias. Valores atuais, sem previsão.",
  maisVendidos: "Mais vendidos",
  top5UnidadesNoPeriodo: "Top 5 · unidades no período",
  rankingIndisponivel: "Ranking indisponível.",
  buscarPerfumeNoRanking: "Buscar perfume no ranking",
  buscarPerfume: "Buscar perfume…",
  maisVendidos2: " Mais vendidos",
  maisFavoritados: " Mais favoritados",
  maisClicados: " Mais clicados",
  osFavoritosDosClientes: "Os favoritos dos clientes",
  interesseNosPerfumes: "Interesse nos perfumes",
  perfumesMaisVendidos: "Perfumes mais vendidos",
  favoritosSalvosAtualmenteTodosOsPeriodos:
    "Favoritos salvos atualmente · todos os períodos",
  cliquesUnicosPorSessaoProdutoEDiaPeriodo:
    "Cliques únicos por sessão, produto e dia · período selecionado",
  pagamentosAprovadosPeriodoSelecionado: "Pagamentos aprovados · período selecionado",
  coletaIniciadaEm30092026CliquesDe:
    "Coleta iniciada em 30/09/2026. Cliques de administradores não são contados. Não representa visitantes únicos.",
  catalogoAgora: "Catálogo agora",
  umaVisaoDaSuaSelecao: "Uma visão da sua seleção.",
  produtosCadastrados: "Produtos cadastrados",
  ativosNaLoja: "Ativos na loja",
  favoritosSalvos: "Favoritos salvos",
  gerenciarCatalogo: "Gerenciar catálogo ",
  atencaoAoEstoque: "Atenção ao estoque",
  produtosAtivosComAte5UnidadesSituacaoAtual:
    "Produtos ativos com até 5 unidades · situação atual",
  verTodos: "Ver todos ↗",
  estoqueIndisponivel: "Estoque indisponível.",
  nenhumProdutoAtivoComEstoqueBaixo: "Nenhum produto ativo com estoque baixo.",
  pagamentosNoPeriodo: "Pagamentos no período",
  statusAtualDosPedidosCriadosNosUltimos: "Status atual dos pedidos criados nos últimos ",
  pedidosIndisponiveis: "Pedidos indisponíveis.",
  gerenciarPedidos: "Gerenciar pedidos ↗",
  confirmado: "Confirmado",
  aprovado: "Aprovado",
  pendente: "Pendente",
  recusado: "Recusado",
  cancelado: "Cancelado",
  reembolsado: "Reembolsado",
  expirado: "Expirado",
  cadastrando: "Cadastrando...",
  alterando: "Alterando...",
  excluindo: "Excluindo...",
  salvando2: "Salvando...",
  entrando: "Entrando...",
  entrar: "Entrar",
  atalhos: "Atalhos",
  desempenho: "Desempenho",
} as const satisfies ContentDictionary;
