import type { ContentDictionary } from "./types";

/** Textos da interface: catalog. */
export const catalogContent = {
  caminhoDeNavegacao: "Caminho de navegação",
  inicio: "Início",
  perfumes: "Perfumes",
  aColecaoBeecah: "A coleção Beecah",
  naoFoiPossivelCarregarEstaSelecao: "Não foi possível carregar esta seleção.",
  tentarNovamente: "Tentar novamente",
  maisVendidos: "Mais vendidos",
  maisRecentes: "Mais recentes",
  erroAoCarregarFavoritos: "Erro ao carregar favoritos:",
  erroAoCarregarProdutosFavoritos: "Erro ao carregar produtos favoritos:",
  minhaConta: "Minha conta",
  meusFavoritos: "Meus favoritos",
  perfumesQueVoceSalvouParaVerDepois: "Perfumes que você salvou para ver depois.",
  seuProximo: "Seu próximo ",
  perfume: "perfume.",
  encontreAFragranciaQueCombinaComVoceExplore:
    "Encontre a fragrância que combina com você. Explore marcas, notas e novas possibilidades.",
  naoFoiPossivelCarregarAColecao: "Não foi possível carregar a coleção.",
  tenteNovamenteEmInstantes: "Tente novamente em instantes.",
  caminhoDoProduto: "Caminho do produto",
  exploreOsDetalhesDaSuaProximaFragrancia:
    "Explore os detalhes da sua próxima fragrância.",
  de: "De ",
  esgotadoNoMomento: "Esgotado no momento",
  disponivel: "Disponível · ",
  entrega: "Entrega",
  consulteOFreteEAsOpcoesDeEnvio:
    "Consulte o frete e as opções de envio na sacola, antes do pagamento.",
  umaAjudaParaEscolher: "Uma ajuda para escolher?",
  converseComABeecah: "Converse com a Beecah ↗",
  conhecaAFragrancia: "Conheça a fragrância",
  alemDo: "Além do ",
  frasco: "frasco.",
  querSaberMaisSobreEstePerfumeFaleCom:
    "Quer saber mais sobre este perfume? Fale com a Beecah para conhecer os detalhes da fragrância.",
  explorarOutrosPerfumes: "Explorar outros perfumes ↗",
  asNotasDoPerfume: "As notas do perfume",
  piramideOlfativa: "Pirâmide olfativa",
  saida: "Saída",
  aPrimeiraImpressao: "A primeira impressão",
  coracao: "Coração",
  aPersonalidadeDaFragrancia: "A personalidade da fragrância",
  fundo: "Fundo",
  asNotasQuePermanecem: "As notas que permanecem",
  asNotasDestaFragranciaAindaNaoForamInformadas:
    "As notas desta fragrância ainda não foram informadas.",
  categorias: "Categorias",
  encontreSeuPerfume: " Encontre seu perfume",
  nomeOuFragrancia: "Nome ou fragrância",
  exYaraAmadeirado: "Ex.: Yara, amadeirado…",
  marca: "Marca",
  todasAsMarcas: "Todas as marcas",
  precoMaximoR: "Preço máximo (R$)",
  semLimite: "Sem limite",
  apenasPerfumesArabes: " Apenas perfumes árabes",
  apenasOfertas: " Apenas ofertas",
  disponiveisEmEstoque: " Disponíveis em estoque",
  limparFiltros: "Limpar filtros",
  perfumeEncontrado: "perfume encontrado",
  perfumesEncontrados: "perfumes encontrados",
  ordenarPor: "Ordenar por",
  menorPreco: "Menor preço",
  maiorPreco: "Maior preço",
  nomeAZ: "Nome A–Z",
  nenhumPerfumePorAqui: "Nenhum perfume por aqui",
  estaSelecaoAindaNaoTemPerfumesDisponiveisExplore:
    "Esta seleção ainda não tem perfumes disponíveis. Explore o catálogo completo.",
  experimenteOutraBuscaOuRemovaOsFiltros: "Experimente outra busca ou remova os filtros.",
  verTodosOsPerfumes: "Ver todos os perfumes",
  precisaDeAjudaParaEscolherFaleComA:
    "Precisa de ajuda para escolher? Fale com a Beecah.",
  arabes: "Árabes",
  colecoesDePerfumes: "Coleções de perfumes",
  voceAindaNaoAdicionouNenhumPerfumeAosFavoritos:
    "Você ainda não adicionou nenhum perfume aos favoritos.",
  verPerfumes: "Ver perfumes",
  erroAoCarregarFavorito: "Erro ao carregar favorito:",
  naoFoiPossivelAdicionarASacolaTenteNovamente:
    "Não foi possível adicionar à sacola. Tente novamente.",
  erroAoRemoverFavorito: "Erro ao remover favorito:",
  erroAoAdicionarFavorito: "Erro ao adicionar favorito:",
  quantidade: "Quantidade",
  diminuirQuantidade: "Diminuir quantidade",
  aumentarQuantidade: "Aumentar quantidade",
  adicionando: "Adicionando…",
  adicionadoASacola: "Adicionado à sacola",
  adicionarASacola: "Adicionar à sacola",
  removerDosFavoritos: "Remover dos favoritos",
  salvarNosFavoritos: "Salvar nos favoritos",
  toqueNoCoracaoParaGuardarSeuFavorito: "Toque no coração para guardar seu favorito.",
  produtoAdicionadoASuaSacola: "Produto adicionado à sua sacola.",
  verMinhaSacola: "Ver minha sacola ",
  esgotado: "Esgotado",
  aSacola: " à sacola",
  adicionadoASacola2: " adicionado à sacola",
  exYaraLattafaMasculino: "Ex: Yara, Lattafa, masculino...",
  categoria: "Categoria",
  precoMinimo: "Preço mínimo",
  precoMaximo: "Preço máximo",
  relevancia: "Relevância",
  produtoEncontrado: "produto encontrado",
  produtosEncontrados: "produtos encontrados",
  nenhumPerfumeEncontrado: "Nenhum perfume encontrado",
  feminino: "Feminino",
  masculino: "Masculino",
  unissex: "Unissex",
  todas: "Todas",
  todos: "Todos",
  femininos: "Femininos",
  masculinos: "Masculinos",
  novos: "Novos",
  perfumesArabes: "Perfumes árabes",
  exploreASelecaoArabeDaBeecahEscolhaPor:
    "Explore a seleção árabe da Beecah. Escolha por gênero, marca ou pelas notas que você gosta.",
  perfumesFemininos: "Perfumes femininos",
  fragranciasFemininasParaDescobrirSuaProximaAssinaturaInclui:
    "Fragrâncias femininas para descobrir sua próxima assinatura. Inclui também os perfumes árabes da coleção.",
  perfumesMasculinos: "Perfumes masculinos",
  exploreOsPerfumesMasculinosIncluindoASelecaoArabe:
    "Explore os perfumes masculinos, incluindo a seleção árabe, e encontre sua próxima escolha.",
  perfumesUnissex: "Perfumes unissex",
  umaSelecaoParaEscolherPeloQueVoceGosta:
    "Uma seleção para escolher pelo que você gosta.",
  novosPerfumes: "Novos perfumes",
  conhecaOsPerfumesMarcadosComoNovidadePelaBeecah:
    "Conheça os perfumes marcados como novidade pela Beecah.",
  osPerfumesMaisVendidosPorQuantidadeEmPedidos:
    "Os perfumes mais vendidos por quantidade em pedidos aprovados. Ranking de todo o período.",
} as const satisfies ContentDictionary;
