import type { ContentDictionary } from "./types";

/** Textos da interface: checkout. */
export const checkoutContent = {
  seuCarrinho: "Seu carrinho",
  suaSacolaEsta: "Sua sacola está",
  vazia: "vazia",
  escolhaUmaFragranciaParaComecarSuaColecao:
    "Escolha uma fragrância para começar sua coleção.",
  verPerfumes: "Ver perfumes",
  tudoQueCabe: "Tudo que cabe",
  naSua: "na sua",
  sacola: "Sacola",
  limparLista: "Limpar lista",
  removerTodosOsProdutosDaSacola: "Remover todos os produtos da sacola?",
  manterProdutos: "Manter produtos",
  esvaziarSacola: "Esvaziar sacola",
  limiteDeEstoqueAtingido: "Limite de estoque atingido",
  removidoDaSacola: " removido da sacola.",
  cada: " cada",
  quantidade: "Quantidade",
  continuarComprando: "Continuar comprando",
  suaSelecao: "Sua seleção",
  resumo: "Resumo",
  daCompra: "da compra",
  fullNamePhone: "\n        full_name,\n        phone\n      ",
  erroAoCarregarPerfilNoCheckout: "Erro ao carregar perfil no checkout:",
  erroAoCarregarEnderecosNoCheckout: "Erro ao carregar endereços no checkout:",
  checkout: "Checkout",
  completeSeusDados: "Complete seus dados",
  paraContinuarACompraPrecisamosDosSeusDados:
    "Para continuar a compra, precisamos dos seus dados pessoais e de um endereço de entrega.",
  dadosPessoais: "Dados pessoais",
  informeSeuNomeETelefone: "Informe seu nome e telefone.",
  completarDados: "Completar dados",
  enderecoDeEntrega: "Endereço de entrega",
  cadastreUmEnderecoParaReceberSeuPedido: "Cadastre um endereço para receber seu pedido.",
  adicionarEndereco: "Adicionar endereço",
  voltarAoCarrinho: "← Voltar ao carrinho",
  confirmeSeuEnderecoDeEntrega: "Confirme seu endereço de entrega",
  escolhaOndeDesejaReceberSeuPedido: "Escolha onde deseja receber seu pedido.",
  endereco: "Endereço",
  principal: "Principal",
  cep: "CEP ",
  editar: "Editar",
  entregarNesteEndereco: "Entregar neste endereço",
  adicionarOutroEndereco: "+ Adicionar outro endereço",
  erroAoCarregarEnderecoEscolhido: "Erro ao carregar endereço escolhido:",
  escolherOutroEndereco: "← Escolher outro endereço",
  confirmarEntrega: "Confirmar entrega",
  confiraOEnderecoSelecionadoAntesDeContinuar:
    "Confira o endereço selecionado antes de continuar.",
  editarEndereco: "Editar endereço",
  continuarParaOFrete: "Continuar para o frete",
  proximaEtapa: "Próxima etapa",
  naProximaTelaVamosCalcularAsOpcoesDe:
    "Na próxima tela vamos calcular as opções de entrega para o CEP ",
  ePermitirQueVoceEscolhaAModalidadeDe:
    " e permitir que você escolha a modalidade de frete antes do pagamento.",
  pagamentoNaoConcluido: "Pagamento não concluído",
  naoFoiPossivelConcluirOPagamento: "Não foi possível concluir o pagamento",
  oPagamentoFoiRecusadoCanceladoOuOcorreuAlgum:
    "O pagamento foi recusado, cancelado ou ocorreu algum problema durante o processo. Você pode tentar novamente pelo carrinho.",
  voltarAoCarrinho2: "Voltar ao carrinho",
  erroAoCarregarEnderecoNoFrete: "Erro ao carregar endereço no frete:",
  voltarParaOEndereco: "← Voltar para o endereço",
  escolhaOFrete: "Escolha o frete",
  selecioneAMelhorOpcaoDeEntregaParaO:
    "Selecione a melhor opção de entrega para o seu pedido.",
  entregarEm: "Entregar em",
  opcoesDeEntrega: "Opções de entrega",
  asOpcoesDeFreteApareceraoAquiAposA:
    "As opções de frete aparecerão aqui após a integração com o Melhor Envio.",
  integracaoPendente: "Integração pendente",
  vamosConsultarOMelhorEnvioUsandoOCep: "Vamos consultar o Melhor Envio usando o CEP",
  osProdutosDoCarrinhoEAsDimensoesPeso:
    ", os produtos do carrinho e as dimensões/peso da embalagem.",
  alterarEndereco: "Alterar endereço",
  continuarParaPagamento: "Continuar para pagamento",
  pagamentoPendente: "Pagamento pendente",
  seuPagamentoEstaEmAnalise: "Seu pagamento está em análise",
  oMercadoPagoAindaEstaProcessandoOPagamento:
    "O Mercado Pago ainda está processando o pagamento. Assim que houver uma atualização, o status do pedido será atualizado automaticamente.",
  minhaConta: "Minha conta",
  erroAoCarregarPedidoAposPagamento: "Erro ao carregar pedido após pagamento:",
  pagamentoAprovado: "Pagamento aprovado",
  pedidoRealizadoComSucesso: "Pedido realizado com sucesso",
  pedido: "Pedido",
  status: "Status",
  total: "Total",
  recebemosORetornoDoSeuPagamentoVocePode:
    "Recebemos o retorno do seu pagamento. Você pode acompanhar o pedido pela sua conta.",
  verPedido: "Ver pedido",
  diaUtil: "dia útil",
  diasUteis: "dias úteis",
  prazoNaoInformado: "Prazo não informado",
  fullNamePhoneCpf:
    "\n            full_name,\n            phone,\n            cpf\n          ",
  naoFoiPossivelCalcularOFrete: "Não foi possível calcular o frete.",
  nenhumaModalidadeDeFreteEstaDisponivelParaEste:
    "Nenhuma modalidade de frete está disponível para este endereço.",
  erroAoCalcularFrete: "Erro ao calcular frete:",
  selecioneUmaModalidadeDeFreteParaContinuar:
    "Selecione uma modalidade de frete para continuar.",
  naoFoiPossivelPrepararOPagamento: "Não foi possível preparar o pagamento.",
  oMercadoPagoNaoRetornouAUrlDe: "O Mercado Pago não retornou a URL de pagamento.",
  erroAoFinalizarCompra: "Erro ao finalizar compra:",
  carregandoResumo: "Carregando resumo...",
  produtosNaSacola: "Produtos na sacola",
  unidades: " unidades",
  entrega: "Entrega",
  entreNaSuaContaParaContinuar: "Entre na sua conta para continuar.",
  completeSeusDadosPessoais: "Complete seus dados pessoais.",
  nenhumEnderecoCadastrado: "Nenhum endereço cadastrado.",
  alterar: "Alterar",
  principal2: " · Principal",
  confirmarEndereco: "Confirmar endereço",
  frete: "Frete",
  informeSeusDadosEEnderecoParaCalcularO:
    "Informe seus dados e endereço para calcular o frete.",
  calculeAsModalidadesDeEntregaDisponiveisParaEste:
    "Calcule as modalidades de entrega disponíveis para este endereço.",
  calculandoFrete: "Calculando frete...",
  calcularFrete: "Calcular frete",
  recalcularFrete: "Recalcular frete",
  produtos: "Produtos",
  aCalcular: "A calcular",
  totalSemFrete: "Total sem frete",
  preparandoPagamento: "Preparando pagamento...",
  entrarParaContinuar: "Entrar para continuar",
  selecioneOFrete: "Selecione o frete",
  finalizarCompra: "Finalizar compra",
  perfume: "Perfume",
  aprovado: "Aprovado",
  pendente: "Pendente",
  recusado: "Recusado",
  cancelado: "Cancelado",
  reembolsado: "Reembolsado",
  atualizando: "Atualizando...",
} as const satisfies ContentDictionary;
