import type { ContentDictionary } from "./types";

/** Textos da interface: store. */
export const storeContent = {
  atendimento: "Atendimento",
  entregaEFrete: "Entrega e frete",
  oValorEAsOpcoesDeFreteSao:
    "O valor e as opções de frete são apresentados durante a compra, de acordo com o endereço de entrega. Confira o endereço e a opção escolhida antes de pagar.",
  irParaMinhaSacola: "Ir para minha sacola",
  acompanheSeuPedido: "Acompanhe seu pedido",
  entreNaSuaContaParaConsultarSeusPedidos:
    "Entre na sua conta para consultar seus pedidos e os detalhes disponíveis. Para dúvidas sobre uma entrega, informe o número do pedido ao atendimento.",
  acessarMinhaConta: "Acessar minha conta",
  trocasEDevolucoes: "Trocas e devoluções",
  paraSolicitarUmaTrocaOuDevolucaoFaleCom:
    "Para solicitar uma troca ou devolução, fale com a Beecah pelo canal de atendimento. Tenha o número do pedido em mãos para que possamos localizar a compra e orientar os próximos passos.",
  falarSobreMeuPedido: "Falar sobre meu pedido",
  seusDados: "Seus dados",
  vocePodeConsultarSeusDadosDeCadastroNa:
    "Você pode consultar seus dados de cadastro na área Minha conta. Para dúvidas sobre privacidade ou solicitações relacionadas aos seus dados, entre em contato com a Beecah.",
  consultarMeuCadastro: "Consultar meu cadastro",
  estamosPorAqui: "Estamos por aqui",
  comoPodemos: "Como podemos ",
  ajudar: "ajudar?",
  escolhaSuaFragranciaTireDuvidasSobreACompra:
    "Escolha sua fragrância, tire dúvidas sobre a compra ou fale sobre seu pedido.",
  conversarNoWhatsapp: " Conversar no WhatsApp",
  beecah: "Beecah",
  naoConseguimosAbrirEstaPagina: "Não conseguimos abrir esta página.",
  tenteNovamenteSePrecisarNossoAtendimentoPodeAjudar:
    "Tente novamente. Se precisar, nosso atendimento pode ajudar.",
  tentarNovamente: "Tentar novamente",
  falarComABeecah: "Falar com a Beecah",
  pularParaOConteudo: "Pular para o conteúdo",
  carregandoALoja: "Carregando a loja",
  carregando: "Carregando…",
  novidadesEmBreve: "Novidades em breve",
  acompanheAsProximasNovidadesDaBeecahCollectionE:
    "Acompanhe as próximas novidades da Beecah Collection e explore a coleção disponível.",
  navegacaoEstrutural: "Navegação estrutural",
  inicio: "Início",
  novidades: "Novidades",
  beecahNovidades: "Beecah / Novidades",
  oProximoCapitulo: "O próximo capítulo",
  aindaVaiChegar: "ainda vai chegar.",
  emBreveEsteEspacoVaiReunirAsNovidades:
    "Em breve, este espaço vai reunir as novidades da nossa coleção. Ainda não há lançamentos ou datas anunciados.",
  enquantoIssoDescubraOsPerfumesQueJaFazem:
    "Enquanto isso, descubra os perfumes que já fazem parte da Beecah.",
  explorarColecao: "Explorar coleção ",
  universoDeFragranciasBeecah: "Universo de fragrâncias Beecah",
  emBreve: "Em breve",
  temUmPerfumeEmMente: "Tem um perfume em mente?",
  contePara: "Conte para ",
  aGente: "a gente.",
  consulteADisponibilidadeDeUmaFragranciaComNosso:
    "Consulte a disponibilidade de uma fragrância com nosso atendimento.",
  falarComABeecah2: "Falar com a Beecah ",
  umaColecaoMuitasPossibilidades: "Uma coleção. Muitas possibilidades.",
  encontreSeuProximoPerfume: "Encontre seu próximo perfume ↗",
  sobreABeecah: "Sobre a Beecah",
  byRebecaHelen: "By Rebeca Helen",
  fragranciasPara: "Fragrâncias para ",
  seusMomentos: "seus momentos.",
  aBeecahReunePerfumesImportadosEArabesPara:
    "A Beecah reúne perfumes importados e árabes para quem quer descobrir uma nova assinatura. Uma coleção para explorar com calma, conhecer as notas e encontrar o que faz sentido para você.",
  dosPerfumesFemininosAosMasculinosEUnissexCada:
    "Dos perfumes femininos aos masculinos e unissex, cada escolha começa pelo seu gosto. Precisa de ajuda? Converse com a gente.",
  explorarColecao2: "Explorar coleção",
  beecahPerfumes: "Beecah Perfumes",
  sBeecah: "%s | Beecah",
  perfumesImportadosArabesFemininosEMasculinosSelecionadosPela:
    "Perfumes importados, árabes, femininos e masculinos selecionados pela Beecah.",
  paginaNaoEncontrada404: "Página não encontrada · 404",
  vamosEncontrarOutroCaminho: "Vamos encontrar outro caminho?",
  esteEnderecoNaoEstaDisponivelExploreNossaColecao:
    "Este endereço não está disponível. Explore nossa coleção para descobrir sua próxima fragrância.",
  explorarPerfumes: "Explorar perfumes",
  visaoGeral: "Visão geral",
  produtos: "Produtos",
  estoque: "Estoque",
  pedidos: "Pedidos",
  clientes: "Clientes",
  banners: "Banners",
  painelAdministrativo: "Painel administrativo",
  perfumes: "Perfumes",
  arabes: "Árabes",
  decante: "— Decante",
  de: "de",
  arabi: "Árabi",
  preco: "Preço",
  homens: "Homens",
  colecao: "Coleção",
  encontreSuaFragrancia: "Encontre sua fragrância",
  explorar: "Explorar",
  mulheres: "Mulheres",
  novasOfertas: "Novas Ofertas",
  seu: "Seu ",
  cheiro: "Cheiro",
  emOferta: "em oferta",
  conhecerOfertas: "Conhecer ofertas",
  osMais: "— Os mais",
  amados: "Amados",
  daColecao: "da Coleção.",
  dificilEscolherSoUm: "Difícil escolher só um.",
  verPerfumes: "Ver perfumes",
  descubraAColecao: "Descubra a coleção",
  nossa: "Nossa",
  selecao: "Seleção",
  produtosAnteriores: "Produtos anteriores",
  proximosProdutos: "Próximos produtos",
  naoFoiPossivelCarregarASelecaoAgora: "Não foi possível carregar a seleção agora.",
  nossaProximaSelecaoEstaChegando: "Nossa próxima seleção está chegando.",
  explorarCatalogo: "Explorar catálogo",
  deslizeParaExplorar: "Deslize para explorar",
  brand1: "Brand 1",
  brand2: "Brand 2",
  brand3: "Brand 3",
  brand4: "Brand 4",
  brand5: "Brand 5",
  compreDe: "Compre de",
  marcas: "Marcas",
  como: "Como",
  explore: "Explore",
  todosOsPerfumes: "Todos os perfumes",
  maisVendidos: "Mais vendidos",
  suaBeecah: "Sua Beecah",
  minhaConta: "Minha conta",
  meusFavoritos: "Meus favoritos",
  minhaSacola: "Minha sacola",
  sobreNos: "Sobre nós",
  podemosAjudar: "Podemos ajudar?",
  acompanharPedido: "Acompanhar pedido",
  beecahCollectionInicio: "Beecah Collection — início",
  beecahCollection: "Beecah Collection",
  fragranciasQueAcompanham: "Fragrâncias que acompanham",
  quemVoceE: "quem você é.",
  conversePeloWhatsapp: "Converse pelo WhatsApp ",
  seuPerfumeSuaPresenca: "Seu perfume. Sua presença.",
  beecahCollection2: " Beecah Collection.",
  privacidade: "Privacidade",
  termosDeUso: "Termos de uso",
  voltarAoTopo: "Voltar ao topo ↑",
  buscarPerfumes: "Buscar perfumes",
  asadLattafa: "Asad Lattafa...",
  perfumesMasculinos: "Perfumes masculinos...",
  perfumesFemininos: "Perfumes femininos...",
  encontreSeuProximoCheiro: "Encontre seu próximo cheiro...",
  feminino: "Feminino",
  masculino: "Masculino",
  abrirMinhaConta: "Abrir minha conta",
  carrinho: "Carrinho",
  favoritos: "Favoritos",
  novos: "Novos",
  criarConta: "Criar conta",
  buscarPerfume: "Buscar perfume...",
  encontreUma: "Encontre uma",
  fragrancia: "Fragrância",
  para: "para",
  chamarDeSua: "chamar de sua.",
  todos: "Todos",
  femininos: "Femininos",
  masculinos: "Masculinos",
  unissex: "Unissex",
  ofertas: "Ofertas",
  selecionadosPelaBeecah: "Selecionados pela Beecah",
  seuProximo: "Seu próximo ",
  favorito: "favorito.",
  escolhaPelasNotasEncontreOSeuEstiloE:
    "Escolha pelas notas, encontre o seu estilo e guarde os perfumes que chamaram sua atenção.",
  verCatalogo: "Ver catálogo ",
  filtrarColecao: "Filtrar coleção",
  naoFoiPossivelCarregarAColecao: "Não foi possível carregar a coleção.",
  tentarPeloCatalogo: "Tentar pelo catálogo",
  aindaNaoHaPerfumesNestaSelecao: "Ainda não há perfumes nesta seleção.",
  verTodos: "Ver todos",
  seusFavoritosFicamGuardadosNoCoracao: "Seus favoritos ficam guardados no coração.",
  explorarCatalogo2: "Explorar catálogo ",
  explorePorCategoria: "Explore por categoria",
  colecaoDePerfumes: "Coleção de perfumes ",
  beecahColecao: "Beecah / Coleção",
  detalhesDeUmPerfumeDaColecao: "Detalhes de um perfume da coleção",
  umOutroJeitoDeEscolher: "Um outro jeito de escolher",
  comecePelasNotas: "Comece pelas notas.",
  exploreOCatalogoPeloTipoDeFragranciaQue:
    "Explore o catálogo pelo tipo de fragrância que você gosta.",
  florais: "Florais",
  floresEDelicadeza: "Flores e delicadeza",
  amadeirados: "Amadeirados",
  madeirasEEspeciarias: "Madeiras e especiarias",
  adocicados: "Adocicados",
  notasDocesEEnvolventes: "Notas doces e envolventes",
  frescos: "Frescos",
  levesEVibrantes: "Leves e vibrantes",
  sobreNosPorRebecaHelen: "Sobre nós · Por Rebeca Helen",
  perfumes2: "Perfumes.",
  ePersonalidade: "E personalidade.",
  arabesImportadosFragranciasParaODiaADia:
    "Árabes, importados, fragrâncias para o dia a dia ou para uma ocasião especial. Na Beecah, a escolha começa pelo que você gosta.",
  confiraAsNotasDeCadaPerfumeOuConverse:
    "Confira as notas de cada perfume ou converse com a gente para encontrar sua próxima escolha.",
  conhecaABeecah: "Conheça a Beecah ",
  faleComAGente: "Fale com a gente ",
  novasDescobertas: "Novas descobertas.",
  emBrevePorAqui: "Em breve, por aqui.",
  haSempreUmaNovaFragranciaParaConhecerEste:
    "Há sempre uma nova fragrância para conhecer. Este será o espaço das próximas novidades da Beecah.",
  acompanharNovidades: "Acompanhar novidades ",
  universoDaColecaoBeecah: "Universo da coleção Beecah",
  antesDeFinalizar: "Antes de finalizar.",
  atendimentoBeecah: "Atendimento Beecah",
  comoConsultoOFrete: "Como consulto o frete?",
  adicioneSeusPerfumesASacolaEInformeO:
    "Adicione seus perfumes à sacola e informe o endereço no fluxo da compra. As opções e os valores disponíveis aparecem antes do pagamento.",
  ondeFicamMeusFavoritos: "Onde ficam meus favoritos?",
  entreNaSuaContaEToqueNoCoracao:
    "Entre na sua conta e toque no coração do perfume. Consulte sua seleção pelo ícone de favoritos ou pelo painel da conta.",
  comoAcompanhoMeusPedidos: "Como acompanho meus pedidos?",
  abraOPainelDaContaEAcesseMeus:
    "Abra o painel da conta e acesse Meus pedidos para consultar suas compras e os detalhes disponíveis.",
  contatoEstamosPorAqui: "Contato / Estamos por aqui",
  suaProximaEscolha: "Sua próxima escolha",
  comecaCom: "começa com ",
  umaConversa: "uma conversa.",
  umaDuvidaSobreAsNotasUmaAjudaPara:
    "Uma dúvida sobre as notas, uma ajuda para escolher ou um pedido para acompanhar. Fale com a Beecah.",
  falarComAGente: "Falar com a gente ",
  precisoDeAjudaComUmPedido: "Preciso de ajuda com um pedido",
  temUmPerfumeQueMarcouASuaHistoria: "Tem um perfume que marcou a sua história?",
  conteSuaExperienciaComABeecah: "Conte sua experiência com a Beecah",
  compartilharMinhaExperiencia: "Compartilhar minha experiência",
  suaProximaFragranciaPodeComecarComUmaConversa:
    "Sua próxima fragrância pode começar com uma conversa.",
  queroAjudaParaEscolher: "Quero ajuda para escolher",
  entreTantasNotasEncontreAsQueCombinamCom:
    "Entre tantas notas, encontre as que combinam com você.",
  exploreAColecaoBeecah: "Explore a coleção Beecah",
  descobrirPerfumes: "Descobrir perfumes",
  encontreiUmaFragranciaParaChamarDeMinha:
    "Encontrei uma fragrância para chamar de minha.",
  clienteDeExemplo01: "Cliente de exemplo · 01",
  umPerfumeQueTransformaPequenosMomentosEmBoas:
    "Um perfume que transforma pequenos momentos em boas lembranças.",
  clienteDeExemplo02: "Cliente de exemplo · 02",
  minhaProximaEscolhaJaTemLugarNosFavoritos:
    "Minha próxima escolha já tem lugar nos favoritos.",
  clienteDeExemplo03: "Cliente de exemplo · 03",
  carrossel: "carrossel",
  previaDepoimentosIlustrativos: "Prévia · depoimentos ilustrativos",
  quemEscolheuABeecah: "Quem escolheu a Beecah",
  historiasQueFicam: "Histórias que ficam",
  suasHistorias: "SUAS HISTÓRIAS",
  suaEssencia: "SUA ESSÊNCIA",
  de5Estrelas: " de 5 estrelas",
  anterior: "Anterior",
  proximo: "Próximo",
  escolherSlide: "Escolher slide",
  irParaSlide: "Ir para slide ",
  prefersReducedMotionReduce: "(prefers-reduced-motion: reduce)",
  fecharPromocao: "Fechar promoção",
  deDesconto: "% de desconto",
  conhecerAOferta: "Conhecer a oferta ",
  continuarNavegando: "Continuar navegando",
  ofertaAnterior: "Oferta anterior",
  proximaOferta: "Próxima oferta",
  ativarSlidesAutomaticos: "Ativar slides automáticos",
  pausarSlides: "Pausar slides",
  relevancia: "Relevância",
  menorPreco: "Menor preço",
  maiorPreco: "Maior preço",
  nomeAZ: "Nome A–Z",
  erroAoCarregarProdutosDaBusca: "Erro ao carregar produtos da busca:",
  naoFoiPossivelCarregarOsPerfumes: "Não foi possível carregar os perfumes.",
  bgPurple50TextPurple700: "\n        bg-purple-50\n        text-purple-700\n      ",
  bgBlue50TextBeecahBlue: "\n        bg-blue-50\n        text-beecah-blue\n      ",
  bgNeutral100TextBeecahBlack70:
    "\n      bg-neutral-100\n      text-beecah-black/70\n    ",
  fecharBusca: "Fechar busca",
  procurePorUmPerfume: "Procure por um perfume...",
  filtrarPor: "Filtrar por",
  filtros: "Filtros",
  refineOsPerfumesExibidos: "Refine os perfumes exibidos",
  limparFiltros: "Limpar filtros",
  categoria: "Categoria",
  marca: "Marca",
  faixaDePreco: "Faixa de preço",
  r: "R$",
  precoMinimo: "Preço mínimo",
  precoMaximo: "Preço máximo",
  ordenarPor: "Ordenar por",
  perfumeEncontrado: "perfume encontrado",
  perfumesEncontrados: "perfumes encontrados",
  filtrosAtivos: "Filtros ativos",
  volumeNaoInformado: "Volume não informado",
  nenhumPerfumeEncontrado: "Nenhum perfume encontrado",
  tentePesquisarOutroNomeMarcaOuCategoria:
    "Tente pesquisar outro nome, marca ou categoria.",
  abrirBuscaDePerfumes: "Abrir busca de perfumes",
  buscarPerfume2: "Buscar perfume",
  abrirBusca: "Abrir busca",
  fecharMenu: "Fechar menu",
  abrirMenu: "Abrir menu",
  beecahLogo: "Beecah Logo",
  entrar: "Entrar",
  todas: "Todas",
  buscar: "Buscar",
} as const satisfies ContentDictionary;
