export const testimonialFormContent = {
  title: "Conte sua experiência",
  intro: "Seu relato será analisado pela Beecah antes de aparecer no site.",
  name: "Nome público",
  namePlaceholder: "Como você quer aparecer no site?",
  instagram: "Instagram (opcional)",
  instagramPlaceholder: "@seuusuario",
  message: "Seu depoimento",
  messagePlaceholder: "Conte como foi sua experiência com a Beecah…",
  consent:
    "Autorizo a publicação deste relato, do meu nome e do Instagram informado no site da Beecah.",
  submit: "Enviar para análise",
  sending: "Enviando…",
  success: "Recebemos seu depoimento! Ele está aguardando aprovação.",
  login: "Entre na sua conta para enviar um depoimento.",
  loginAction: "Entrar na conta",
  pending: "Você já tem um depoimento aguardando análise.",
  invalid:
    "Confira o nome (2–80 caracteres), o texto (20–1.000 caracteres), o Instagram e a autorização.",
  failed: "Não foi possível enviar agora. Tente novamente.",
  tooSoon: "Aguarde 24 horas entre os envios de depoimentos.",
  adminTitle: "Comentários",
  adminIntro: "Revise os depoimentos antes de publicá-los na loja.",
  approved: "Aprovados",
  pendingLabel: "Pendentes",
  rejected: "Rejeitados",
  approve: "Aprovar e publicar",
  reject: "Rejeitar",
  unpublish: "Retirar do site",
  updated: "Moderação atualizada.",
  updateFailed: "Não foi possível atualizar o comentário.",
  empty: "Nenhum comentário nesta aba.",
  previous: "Anterior",
  next: "Próxima",
  loadFailed: "Não foi possível carregar os comentários. Atualize a página.",
} as const;
